if(NOT DEFINED APP OR NOT DEFINED ROOT)
  message(FATAL_ERROR "APP and ROOT required")
endif()
file(MAKE_DIRECTORY "${ROOT}")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run)
foreach(mode restore discard conflict cancel corrupt)
  set(project "${ROOT}/Autosave ä ${run} ${mode}")
  execute_process(COMMAND "${APP}" --autosave-crash "${project}" RESULT_VARIABLE result
                  OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Autosave writer ${mode}: ${result}\n${output}\n${errors}")
  endif()
  file(READ "${project}/main.c" original_main)
  file(READ "${project}/analysis.c" original_analysis)
  if(mode STREQUAL conflict)
    file(APPEND "${project}/main.c" "\n/* external edit */\n")
  elseif(mode STREQUAL corrupt)
    file(WRITE "${project}/.physim-autosave" "damaged snapshot")
  endif()
  execute_process(COMMAND "${APP}" --autosave-recover "${project}" "${mode}"
                  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Recovery ${mode}: ${result}\n${output}\n${errors}")
  endif()
  if(mode STREQUAL cancel)
    if(NOT EXISTS "${project}/.physim-autosave")
      message(FATAL_ERROR "Closing recovery lost snapshot")
    endif()
    file(READ "${project}/main.c" after_main)
    file(READ "${project}/analysis.c" after_analysis)
    if(NOT after_main STREQUAL original_main OR NOT after_analysis STREQUAL original_analysis)
      message(FATAL_ERROR "Closing recovery changed sources")
    endif()
  elseif(mode STREQUAL corrupt)
    file(READ "${project}/.physim-autosave" damaged)
    if(NOT damaged STREQUAL "damaged snapshot")
      message(FATAL_ERROR "Damaged snapshot was overwritten")
    endif()
  endif()
endforeach()
message(STATUS "Abrupt process exit, restore, discard, external changes, cancel and corrupt recovery passed")
