cmake_minimum_required(VERSION 3.24)
foreach(required COMPILER WORK SOURCE_DIR C_COMPILER GENERATOR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}/sources ä")
set(project "${WORK}/sources ä")
include("${CMAKE_CURRENT_LIST_DIR}/language_corpus.cmake")
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_runtime_cases.json" runtime_corpus)
string(JSON version GET "${runtime_corpus}" format)
if(NOT version EQUAL 1)
  message(FATAL_ERROR "Unsupported native runtime test corpus")
endif()
string(JSON count LENGTH "${runtime_corpus}" programs)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  string(JSON record GET "${runtime_corpus}" programs ${index})
  string(JSON case GET "${record}" name)
  list(APPEND cases "${case}")
  set(record_${case} "${record}")
  string(JSON source_file ERROR_VARIABLE absent GET "${record}" source_file)
  if(NOT absent)
    file(READ "${SOURCE_DIR}/${source_file}" code)
  else()
    string(JSON code GET "${record}" source)
  endif()
  string(JSON count ERROR_VARIABLE absent LENGTH "${record}" repeat_tokens)
  if(NOT absent AND count GREATER 0)
    math(EXPR token_last "${count} - 1")
    foreach(token_index RANGE ${token_last})
      string(JSON token MEMBER "${record}" repeat_tokens ${token_index})
      string(JSON repeated GET "${record}" repeat_tokens "${token}" text)
      string(JSON repetitions GET "${record}" repeat_tokens "${token}" count)
      string(REPEAT "${repeated}" ${repetitions} replacement)
      string(REPLACE "${token}" "${replacement}" code "${code}")
    endforeach()
  endif()
  string(REPLACE "\r\n" "\n" code "${code}")
  file(WRITE "${project}/${case}.phys" "${code}")
endforeach()
set(project_text "cmake_minimum_required(VERSION 3.24)\nproject(GeneratedLanguage C)\nset(CMAKE_C_STANDARD 17)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\n")
string(APPEND project_text "include_directories(\"${SOURCE_DIR}/include\")\n")
string(APPEND project_text "include(\"${SOURCE_DIR}/cmake/PhysimLanguage.cmake\")\nset(PHYSIM_COMPILER \"${COMPILER}\")\n")
foreach(case IN LISTS cases)
  execute_process(COMMAND "${COMPILER}" --emit-c "${project}/${case}.phys"
    RESULT_VARIABLE result OUTPUT_FILE "${project}/${case}.c" ERROR_VARIABLE error TIMEOUT 15)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "C emission failed for ${case}: ${result}\n${error}")
  endif()
  string(JSON balance ERROR_VARIABLE absent GET "${record_${case}}" memory_balance)
  if(NOT absent AND balance)
    file(READ "${project}/${case}.c" generated)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/language_memory_balance.h" harness)
    file(WRITE "${project}/${case}.c" "#define main ps_test_main\n${generated}\n${harness}")
  endif()
  if(case STREQUAL "native")
    string(APPEND project_text "physim_add_program(native native.phys)\n")
  else()
    string(APPEND project_text "add_executable(${case} ${case}.c)\n")
    string(APPEND project_text "target_link_libraries(${case} PRIVATE physim_language_sdk)\n")
  endif()
  string(APPEND project_text "set_target_properties(${case} PROPERTIES RUNTIME_OUTPUT_DIRECTORY \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_DEBUG \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_RELEASE \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO \"${WORK}/bin\")\n")
  if(NOT WIN32)
    string(APPEND project_text "target_link_libraries(${case} PRIVATE m)\n")
  endif()
endforeach()
file(WRITE "${project}/source_map_probe.phys" "func mapped():\n    let value = 1\nmapped()\n")
execute_process(COMMAND "${COMPILER}" --emit-c "${project}/source_map_probe.phys"
  RESULT_VARIABLE result OUTPUT_VARIABLE mapped_c ERROR_VARIABLE error TIMEOUT 15)
if(NOT result EQUAL 0 OR NOT mapped_c MATCHES "#line 1 " OR
   NOT mapped_c MATCHES "#line 2 " OR NOT error STREQUAL "")
  message(FATAL_ERROR "Source line emission failed: ${result}\n${error}")
endif()
string(FIND "${mapped_c}" "#line 1 " marker)
string(SUBSTRING "${mapped_c}" ${marker} -1 after_marker)
string(FIND "${after_marker}" "\n" line_end)
math(EXPR insertion "${marker} + ${line_end} + 1")
string(SUBSTRING "${mapped_c}" 0 ${insertion} before_error)
string(SUBSTRING "${mapped_c}" ${insertion} -1 after_error)
file(WRITE "${project}/source_map_probe.c"
  "${before_error}#error PHYSIM_SOURCE_MAP_PROBE\n${after_error}")
string(APPEND project_text "add_executable(source_map_probe EXCLUDE_FROM_ALL source_map_probe.c)\n")
file(WRITE "${project}/CMakeLists.txt" "${project_text}")
set(options -G "${GENERATOR}" "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_C_FLAGS=${C_FLAGS}")
if(DEFINED MAKE_PROGRAM AND NOT MAKE_PROGRAM STREQUAL "")
  list(APPEND options "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(NOT CONFIG)
  set(CONFIG Debug)
endif()
list(APPEND options "-DCMAKE_BUILD_TYPE=${CONFIG}")
# ASan/MSVC cannot link incrementally.
if(WIN32 AND C_FLAGS MATCHES "/fsanitize=address")
  list(APPEND options "-DCMAKE_EXE_LINKER_FLAGS=/INCREMENTAL:NO")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${project}" -B "${WORK}/build" ${options}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Generated project configure failed: ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}" --parallel 4
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 180)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native compilation failed (${result}): ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}"
  --target source_map_probe RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
  TIMEOUT 60)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "source_map_probe.phys" OR
   NOT "${output}${error}" MATCHES "PHYSIM_SOURCE_MAP_PROBE")
  message(FATAL_ERROR "Native compiler lost Physim source location: ${result}\n${output}\n${error}")
endif()
if(WIN32)
  set(extension .exe)
endif()
foreach(case IN LISTS cases)
  execute_process(COMMAND "${WORK}/bin/${case}${extension}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  string(REPLACE "\r\n" "\n" output "${output}")
  string(REPLACE "\r\n" "\n" error "${error}")
  physim_language_expect("${record_${case}}" "${result}" "${output}" "${error}")
endforeach()
file(SHA256 "${WORK}/build/native.physim.c" previous_generated)
file(WRITE "${project}/native.phys" "let immutable = 1\nimmutable = 2\n")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}" --target native
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
file(SHA256 "${WORK}/build/native.physim.c" failed_generated)
configure_file("${SOURCE_DIR}/tests/fixtures/language/native.phys" "${project}/native.phys" COPYONLY)
if(result EQUAL 0 OR NOT previous_generated STREQUAL failed_generated OR
   EXISTS "${WORK}/build/native.physim.c.tmp")
  message(FATAL_ERROR "Failed source must stop build and preserve last complete generated file")
endif()
message(STATUS "Native C17: source-order evaluation, recursion, loops, strings, arithmetic and runtime diagnostics passed")
