foreach(required COMPILER WORK SOURCE_DIR C_COMPILER GENERATOR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}/sources ä")
set(project "${WORK}/sources ä")
list(APPEND matrix_cases matrixindex3 matrixindex4 matrixsingular3 matrixsingular4
  matrixtolerance matrixrotation matrixdirection matrixnormal matrixnormalzero
  matrixpointzero matrixmultiplyoverflow matrixapplyoverflow matrixinverseoverflow)
set(matrixindex3 "let v = Mat3.identity().element(-1,0)\n")
set(matrixindex4 "let v = Mat4.identity().element(0,9223372036854775807)\n")
set(matrixsingular3 "let v = Vec3(0,0,0)\nlet m = Mat3(v,v,v).inverse(0)\n")
set(matrixsingular4 "let m = Mat4.scale(Vec3(1,0,1)).inverse(0)\n")
set(matrixtolerance "let m = Mat3.identity().inverse(1)\n")
set(matrixrotation "let m = Mat4.rotation(Quat(0,0,0,0))\n")
set(matrix_projective "let m = Mat4(Vec4(1,0,0,0),Vec4(0,1,0,0),Vec4(0,0,1,1),Vec4(0,0,0,1))\n")
set(matrixdirection "${matrix_projective}let v = m.transformDirection(Vec3(1,2,3))\n")
set(matrixnormal "${matrix_projective}let v = m.transformNormal(Vec3(1,2,3))\n")
set(matrixnormalzero "let v = Mat4.identity().transformNormal(Vec3(0,0,0))\n")
set(matrixpointzero "${matrix_projective}let v = m.transformPoint(Vec3(1,2,-1))\n")
set(matrixmultiplyoverflow "let m = Mat4.scale(Vec3(1e308,1,1))\nlet v = m.multiplied(m)\n")
set(matrixapplyoverflow "let m = Mat3(Vec3(1e308,0,0),Vec3(0,1,0),Vec3(0,0,1))\nlet v = m.applied(Vec3(2,0,0))\n")
set(matrixinverseoverflow "let m = Mat4.scale(Vec3(1e-320,1,1)).inverse(0)\n")
set(expected_matrixindex3 "Mat3 row and column")
set(expected_matrixindex4 "Mat4 row and column")
set(expected_matrixsingular3 "Matrix operation is singular")
set(expected_matrixsingular4 "Matrix operation is singular")
set(expected_matrixtolerance "Invalid matrix operation arguments")
set(expected_matrixrotation "Invalid matrix operation arguments")
set(expected_matrixdirection "Invalid matrix operation arguments")
set(expected_matrixnormal "Invalid matrix operation arguments")
set(expected_matrixnormalzero "Invalid matrix operation arguments")
set(expected_matrixpointzero "Matrix operation is singular")
set(expected_matrixmultiplyoverflow "Non-finite")
set(expected_matrixapplyoverflow "Non-finite")
set(expected_matrixinverseoverflow "Matrix operation exceeds numeric range")
file(READ "${SOURCE_DIR}/tests/fixtures/language/arrays.phys" arrays)
file(READ "${SOURCE_DIR}/examples/language/particles.phys" particles)
set(cases native records enums conversions sdk longliteral add sub mul neg divzero divoverflow modzero floatzero floatoverflow literal globalread globalwrite fieldread fieldwrite recursion assertion assertionmessage uniterror domainerror mathlogdomain mathpowdomain mathexpoverflow mathatan2zero mathhypotoverflow conversionupper conversionlower conversionroundtrip vectorzero vectoroverflow vectorlength vectordot)
list(APPEND cases bitwise bitshiftnegative bitshiftlarge)
file(READ "${SOURCE_DIR}/tests/fixtures/language/bitwise.phys" bitwise)
list(APPEND cases enum_methods)
file(READ "${SOURCE_DIR}/tests/fixtures/language/enum_methods.phys" enum_methods)
list(APPEND cases unicode_identifiers)
file(READ "${SOURCE_DIR}/tests/fixtures/language/unicode_identifiers.phys" unicode_identifiers)
list(APPEND cases numeric_bounds clampinverted)
file(READ "${SOURCE_DIR}/tests/fixtures/language/numeric_bounds.phys" numeric_bounds)
set(clampinverted "let value = clamp(0.0, 2.0, 1.0)\n")
list(APPEND cases switch_wildcards)
file(READ "${SOURCE_DIR}/tests/fixtures/language/switch_wildcards.phys" switch_wildcards)
list(APPEND cases bezier_curve beziernegative bezierupper beziertangentoverflow)
file(READ "${SOURCE_DIR}/tests/fixtures/language/bezier_curve.phys" bezier_curve)
set(bezier_setup "let c = Bezier3(Vec3(0,0,0),Vec3(1,0,0),Vec3(1,1,0),Vec3(1,1,1))\n")
set(beziernegative "${bezier_setup}let p = c.position(-0.1)\n")
set(bezierupper "${bezier_setup}let p = c.splitRight(1.1)\n")
set(beziertangentoverflow "let c = Bezier3(Vec3(1e308,0,0),Vec3(-1e308,0,0),Vec3(0,0,0),Vec3(0,0,0))\nlet p = c.tangent(0)\n")
list(APPEND cases linear_solve linearsingular linearshape linearempty linearupper lineartolerance linearnumeric)
file(READ "${SOURCE_DIR}/tests/fixtures/language/linear_solve.phys" linear_solve)
list(APPEND cases scalar_search scalarbracket scalarlimit scalariterations)
file(READ "${SOURCE_DIR}/tests/fixtures/language/scalar_search.phys" scalar_search)
list(APPEND cases scalar_report scalarreportbracket scalarreportcallback)
file(READ "${SOURCE_DIR}/tests/fixtures/language/scalar_report.phys" scalar_report)
list(APPEND cases ode_step odeempty odeupper odebadstep odeshape odeinner odenumeric)
file(READ "${SOURCE_DIR}/tests/fixtures/language/ode_step.phys" ode_step)
list(APPEND cases rk45_integrate rk45empty rk45upper rk45budget rk45badoptions rk45badsteps rk45zerostep rk45limit rk45shape rk45inner)
file(READ "${SOURCE_DIR}/tests/fixtures/language/rk45_integrate.phys" rk45_integrate)
list(APPEND cases rk45toleranceshape rk45tolerancevalue)
list(APPEND cases rk45_report rk45reportbudget rk45reportcallback rk45reporttoleranceshape rk45reporttolerancevalue)
file(READ "${SOURCE_DIR}/tests/fixtures/language/rk45_report.phys" rk45_report)
list(APPEND cases verlet_step verletempty verletodd verletupper verletbadstep verletshape verletinner)
file(READ "${SOURCE_DIR}/tests/fixtures/language/verlet_step.phys" verlet_step)
set(ode_function "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    return state\n")
set(odeempty "${ode_function}let state: [Float64] = []\nlet next = eulerStep(derivative,state,0,0.1)\n")
set(odeupper "${ode_function}var state: [Float64] = []\nfor i in 0..<33:\n    state.append(1.0)\nlet next = rk4Step(derivative,state,0,0.1)\n")
set(odebadstep "${ode_function}let next = eulerStep(derivative,[1.0],0,0)\n")
set(odeshape "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    return [1.0]\nlet next = rk4Step(derivative,[1.0,0.0],0,0.1)\n")
set(odeinner "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    assert(false)\n    return state\nlet next = rk4Step(derivative,[1.0],0,0.1)\n")
set(odenumeric "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    return [1e308]\nlet next = eulerStep(derivative,[1e308],0,1)\n")
set(rk45empty "${ode_function}let state: [Float64] = []\nlet next = rk45Integrate(derivative,state,0,1,1e-9,1e-7,100)\n")
set(rk45upper "${ode_function}var state: [Float64] = []\nfor i in 0..<33:\n    state.append(1.0)\nlet next = rk45Integrate(derivative,state,0,1,1e-9,1e-7,100)\n")
set(rk45budget "${ode_function}let next = rk45Integrate(derivative,[1.0],0,1,1e-9,1e-7,0)\n")
set(rk45badoptions "${ode_function}let next = rk45Integrate(derivative,[1.0],0,1,-1,1e-7,100)\n")
set(rk45badsteps "${ode_function}let next = rk45IntegrateWithSteps(derivative,[1.0],0,1,1e-9,1e-7,100,0.1,0.2,0.1)\n")
set(rk45zerostep "${ode_function}let next = rk45IntegrateWithSteps(derivative,[1.0],0,1,1e-9,1e-7,100,0,1e-14,1)\n")
set(rk45limit "${ode_function}let next = rk45Integrate(derivative,[1.0],0,2,1e-11,1e-11,1)\n")
set(rk45shape "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    return [1.0]\nlet next = rk45Integrate(derivative,[1.0,0.0],0,1,1e-9,1e-7,100)\n")
set(rk45inner "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    assert(false)\n    return state\nlet next = rk45Integrate(derivative,[1.0],0,1,1e-9,1e-7,100)\n")
set(rk45toleranceshape "${ode_function}let next = rk45IntegrateWithTolerances(derivative,[1.0,2.0],0,1,[1e-9],1e-7,100,0.1,1e-14,1)\n")
set(rk45tolerancevalue "${ode_function}let next = rk45IntegrateWithTolerances(derivative,[1.0],0,1,[0.0],1e-7,100,0.1,1e-14,1)\n")
set(rk45reportbudget "${ode_function}let result = rk45IntegrateReported(derivative,[1.0],0,1,1e-9,1e-7,0,0.1,1e-14,1)\n")
set(rk45reportcallback "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    assert(false)\n    return state\nlet result = rk45IntegrateReported(derivative,[1.0],0,1,1e-9,1e-7,100,0.1,1e-14,1)\n")
set(rk45reporttoleranceshape "${ode_function}let result = rk45IntegrateWithTolerancesReported(derivative,[1.0,2.0],0,1,[1e-9],1e-7,100,0.1,1e-14,1)\n")
set(rk45reporttolerancevalue "${ode_function}let result = rk45IntegrateWithTolerancesReported(derivative,[1.0],0,1,[0.0],1e-7,100,0.1,1e-14,1)\n")
set(verletempty "${ode_function}let phase: [Float64] = []\nlet next = verletStep(derivative,phase,0,0.1)\n")
set(verletodd "${ode_function}let next = verletStep(derivative,[1.0,0.0,0.0],0,0.1)\n")
set(verletupper "${ode_function}var phase: [Float64] = []\nfor i in 0..<66:\n    phase.append(1.0)\nlet next = verletStep(derivative,phase,0,0.1)\n")
set(verletbadstep "${ode_function}let next = verletStep(derivative,[1.0,0.0],0,0)\n")
set(verletshape "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    return [1.0]\nlet next = verletStep(derivative,[1.0,2.0,0.0,0.0],0,0.1)\n")
set(verletinner "func derivative(time: Float64, state: [Float64]) -> [Float64]:\n    assert(false)\n    return state\nlet next = verletStep(derivative,[1.0,0.0],0,0.1)\n")
set(scalar_function "func target(x: Float64) -> Float64:\n    return x * x - 2\n")
set(scalarbracket "${scalar_function}let x = rootBisect(target, 2, 3, 1e-9, 0, 100)\n")
set(scalarlimit "${scalar_function}let x = rootBisect(target, 1, 2, 1e-30, 0, 1)\n")
set(scalariterations "${scalar_function}let x = minimizeGolden(target, 1, 2, 1e-9, 0, 0)\n")
set(scalarreportbracket "${scalar_function}let result = rootBisectReported(target, 2, 3, 1e-9, 0, 100)\n")
set(scalarreportcallback "func target(x: Float64) -> Float64:\n    assert(false)\n    return x\nlet result = minimizeGoldenReported(target, 0, 2, 1e-9, 0, 100)\n")
set(linearsingular "let x = linearSolve([1.0,2.0,2.0,4.0],[3.0,6.0],0)\n")
set(linearshape "let x = linearSolve([1.0,2.0,3.0],[1.0,2.0],0)\n")
set(linearempty "let a: [Float64] = []\nlet x = linearSolve(a,a,0)\n")
set(linearupper "var rhs: [Float64] = []\nfor i in 0..<33:\n    rhs.append(1.0)\nlet coefficients: [Float64] = []\nlet x = linearSolve(coefficients,rhs,0)\n")
set(lineartolerance "let x = linearSolve([1.0],[2.0],-0.1)\n")
set(linearnumeric "let x = linearSolve([1e-300],[1e300],0)\n")
set(bitshiftnegative "let value = 1 << -1\n")
set(bitshiftlarge "let value = -1 >> 64\n")
list(APPEND cases ${matrix_cases})
list(APPEND cases optionalvalues optionalunwrap optionalnested optionalfallback optionalargument optionalbudget optionalswitcherror)
file(READ "${SOURCE_DIR}/examples/language/optional_values.phys" optionalvalues)
set(optionalunwrap "let x: [Int64]? = nil\nlet y = x.unwrap()\n")
set(optionalnested "let x: Int64?? = Optional.some(nil)\nlet y = x.unwrap().unwrap()\n")
set(optionalfallback "func fail() -> [Int64]:\n    let own = Optional.some([[1],[2]])\n    let x: Int64? = nil\n    let n = x.unwrap()\n    return [n]\nlet x = Optional.some([1]).valueOr(fail())\n")
set(optionalargument "func fail() -> [Int64]:\n    let own = Optional.some([[1],[2]])\n    assert(false)\n    return [1]\nlet x = Optional.some(fail())\n")
set(optionalbudget "struct Node:\n    let matrix: Mat4\n    let next: Node?\nvar root: Node? = nil\nfor i in 0..<1000000:\n    root = Optional.some(Node(Mat4.identity(),root))\n")
set(optionalswitcherror "func fail(items: [[Int64]]) -> Bool:\n    assert(items.count == 2)\n    assert(false)\n    return true\nlet value = Optional.some([[1],[2]])\nswitch value:\n    case Optional.some(items) if fail(items):\n        print(1)\n    default:\n        print(0)\n")
set(expected_optionalunwrap "Cannot unwrap nil optional")
set(expected_optionalnested "Cannot unwrap nil optional")
set(expected_optionalfallback "Cannot unwrap nil optional")
set(expected_optionalargument "Assertion failed")
set(expected_optionalswitcherror "Assertion failed")
set(expected_structdefaulterror "Assertion failed")
set(expected_optionalbudget "memory budget")
list(APPEND cases optionalbindings optionalbindingerror optionalbindingcondition)
file(READ "${SOURCE_DIR}/examples/language/optional_bindings.phys" optionalbindings)
set(optionalbindingerror "if var rows = Optional.some([[1],[2]]):\n    rows[0].append(3)\n    while let values = Optional.some(rows):\n        assert(false)\n")
set(optionalbindingcondition "func next() -> [Int64]?:\n    let retained = Optional.some([1])\n    assert(false)\n    return nil\nwhile let value = next():\n    print(1)\n")
set(expected_optionalbindingerror "Assertion failed")
set(expected_optionalbindingcondition "Assertion failed")
list(APPEND cases arrays arraynegative arrayupper arrayreturnerror)
list(APPEND cases particles)
list(APPEND cases structdefaulterror)
set(structdefaulterror "func fail() -> Int64:\n    assert(false)\n    return 0\nstruct S:\n    let owned: [Int64] = [1, 2]\n    let failed: Int64 = fail()\nlet value = S()\n")
list(APPEND cases arraybudget arraypartial)
list(APPEND cases arrayiterationerror)
list(APPEND cases arraymethods arraymethoderror arraymethodrecursion)
list(APPEND cases mutating)
list(APPEND cases sensors sensorconfig sensorunit sensortime sensorrange distributioninvalid)
file(READ "${SOURCE_DIR}/tests/fixtures/language/sensors.phys" sensors)
set(sensor_setup "let m = Unit(1,0,0,0,0,0,0,1,\"m\")\nlet config = SensorConfig(m,10,0,0,0,0,Distribution.constant(0),0,0,0)\nvar s = Sensor(config,0)\n")
set(sensorconfig "let m = Unit(1,0,0,0,0,0,0,1,\"m\")\nlet c = SensorConfig(m,0,0,0,0,0,Distribution.constant(0),0,0,0)\n")
set(sensorunit "${sensor_setup}let q = Quantity(1, Unit(0,0,1,0,0,0,0,1,\"s\"))\nlet x = s.read(0,q)\n")
set(sensortime "${sensor_setup}let q = Quantity(1,m)\nlet first = s.read(1,q)\nlet x = s.read(0,q)\n")
set(sensorrange "${sensor_setup}let x = s.read(1e20,Quantity(1,m))\n")
set(distributioninvalid "let d = Distribution.uniform(1,0)\n")
set(expected_sensorconfig "Invalid sensor configuration")
set(expected_sensorunit "Sensor read failed")
set(expected_sensortime "Sensor read failed")
set(expected_sensorrange "Sensor read failed")
set(expected_distributioninvalid "Invalid distribution parameters")
list(APPEND cases units unitmultiplyoverflow unitdivideoverflow unitpoweroverflow unitpowerwide unitscaleoverflow unitscaleunderflow)
file(READ "${SOURCE_DIR}/tests/fixtures/language/units.phys" units)
set(unitmultiplyoverflow "let u = Unit(127, 0, 0, 0, 0, 0, 0, 1, \"m127\")\nlet x = u.multiplied(u, \"bad\")\n")
set(unitdivideoverflow "let u = Unit(-128, 0, 0, 0, 0, 0, 0, 1, \"m-128\")\nlet m = Unit(1, 0, 0, 0, 0, 0, 0, 1, \"m\")\nlet x = u.divided(m, \"bad\")\n")
set(unitpoweroverflow "let u = Unit(1, 0, 0, 0, 0, 0, 0, 1, \"m\")\nlet x = u.powered(128, \"bad\")\n")
set(unitpowerwide "let u = Unit(0, 0, 0, 0, 0, 0, 0, 1, \"1\")\nlet x = u.powered(9223372036854775807, \"bad\")\n")
set(unitscaleoverflow "let u = Unit(1, 0, 0, 0, 0, 0, 0, 1e200, \"huge\")\nlet x = u.powered(2, \"bad\")\n")
set(unitscaleunderflow "let u = Unit(1, 0, 0, 0, 0, 0, 0, 1e-200, \"tiny\")\nlet x = u.multiplied(u, \"bad\")\n")
set(expected_unitmultiplyoverflow "Unit exponent exceeds")
set(expected_unitdivideoverflow "Unit exponent exceeds")
set(expected_unitpoweroverflow "Unit exponent exceeds")
set(expected_unitpowerwide "Unit power exceeds")
set(expected_unitscaleoverflow "Unit scale is not positive and finite")
set(expected_unitscaleunderflow "Unit scale is not positive and finite")
list(APPEND cases quantitydimension quantityzero quantityoverflow quantityunderflow)
set(quantitydimension "let m = Unit(1, 0, 0, 0, 0, 0, 0, 1, \"m\")\nlet s = Unit(0, 0, 1, 0, 0, 0, 0, 1, \"s\")\nfunc dynamicUnit() -> Unit:\n    return s\nlet q = Quantity(1, m).adding(Quantity(1, dynamicUnit()))\n")
set(quantityzero "let u = Unit(0, 0, 0, 0, 0, 0, 0, 1, \"1\")\nlet q = Quantity(1, u).divided(Quantity(0, u), \"1\")\n")
set(quantityoverflow "let u = Unit(0, 0, 0, 0, 0, 0, 0, 1, \"1\")\nlet q = Quantity(1e308, u).adding(Quantity(1e308, u))\n")
set(quantityunderflow "let u = Unit(0, 0, 0, 0, 0, 0, 0, 1, \"1\")\nlet q = Quantity(1e-200, u).multiplied(Quantity(1e-200, u), \"1\")\n")
set(expected_quantitydimension "Invalid quantity operation")
set(expected_quantityzero "Invalid quantity operation")
set(expected_quantityoverflow "Quantity result or scale is not representable")
set(expected_quantityunderflow "Quantity result or scale is not representable")
set(mutating "struct Counter:\n    var n: Int64\n    mutating func add(value: Int64) -> Int64:\n        self.n += value\n        return self.n\n    mutating func reset():\n        self = Counter(0)\n        return\nstruct Group:\n    var counter: Counter\nvar group = Group(Counter(1))\nlet before = group\nassert(group.counter.add(2) == 3)\nassert(group.counter.n == 3 && before.counter.n == 1)\ngroup.counter.reset()\nassert(group.counter.n == 0)\n")
file(READ "${SOURCE_DIR}/tests/fixtures/language/arraymethods.phys" arraymethods)
set(arraymethoderror "struct S:\n    let a: [Int64]\n    func fail():\n        let copy = self\n        assert(false)\nS([1]).fail()\n")
set(arraymethodrecursion "struct S:\n    let a: [Int64]\n    func recurse():\n        self.recurse()\nS([1]).recurse()\n")
list(APPEND cases arrayappenderror arrayappendindex)
list(APPEND cases arrayremovemethod)
set(arrayremovemethod "var a: [[Int64]] = []\nlet removed = a.remove(at: 0)\n")
set(arrayappenderror "var a = [[1]]\nfunc fail() -> [Int64]:\n    let owned = [[2]]\n    assert(false)\n    return owned[0]\na.append(fail())\n")
set(arrayappendindex "var a = [[1]]\na[1].append(2)\n")
list(APPEND cases arrayslicenegative arrayslicereversed arraysliceupper arraysliceclosed
                  arrayslicemax arraysliceempty arraysliceerror)
list(APPEND cases arrayrangereversed arrayrangeupper arrayrangeclosed arrayrangeempty
                  arrayrangeerror)
list(APPEND cases arrayopenupper arrayopenlower arrayopenclosed arrayopenassign)
list(APPEND cases strideloopzero strideslicezero stridescatterzero
                  stridescattercount)
set(strideloopzero "for i in 0..<5 by 0:\n    print(i)\n")
set(strideslicezero "let a = [[1], [2]][... by 0]\n")
set(stridescatterzero "var a = [[1], [2]]\na[... by 0] = [[3], [4]]\n")
set(stridescattercount "var a = [[1], [2], [3]]\na[... by 2] = [[4]]\n")
set(arrayopenupper "let a = [[1]][..<2]\n")
set(arrayopenlower "let a = [[1]][2..<]\n")
set(arrayopenclosed "let a = [[1]][...1]\n")
set(arrayopenassign "var a = [[1]]\nfunc rhs() -> [[Int64]]:\n    assert(false)\n    return [[2]]\na[2..<] = rhs()\n")
set(arrayrangereversed "var a = [[1], [2]]\nfunc rhs() -> [[Int64]]:\n    assert(false)\n    return [[3]]\na[1..<0] = rhs()\n")
set(arrayrangeupper "var a = [[1]]\na[0..<2] = [[3]]\n")
set(arrayrangeclosed "var a = [[1]]\na[0...1] = [[3]]\n")
set(arrayrangeempty "var a: [[Int64]] = []\na[0...0] = [[3]]\n")
set(arrayrangeerror "var a = [[1], [2]]\na[0...0] = [[3]]\nassert(false)\n")
set(arrayslicenegative "let a = [[1]][-1..<0]\n")
set(arrayslicereversed "let a = [[1], [2]][1..<0]\n")
set(arraysliceupper "let a = [[1]][0..<2]\n")
set(arraysliceclosed "let a = [[1]][0...1]\n")
set(arrayslicemax "let a = [[1]][0...9223372036854775807]\n")
set(arraysliceempty "let empty: [[Int64]] = []\nlet a = empty[0...0]\n")
set(arraysliceerror "let a = [[1], [2]][0...0]\nassert(false)\n")
list(APPEND cases arrayremovenegative arrayremoveupper arrayremoveempty)
list(APPEND cases stringindexnegative stringindexupper stringsliceclosed stringstepzero)
set(stringindexnegative "let text = \"Grüße\"\nlet ch = text[-1]\n")
set(stringindexupper "let text = \"Grüße\"\nlet ch = text[5]\n")
set(stringsliceclosed "let text = \"Grüße\"\nlet part = text[0...5]\n")
set(stringstepzero "let text = \"Grüße\"\nlet part = text[... by 0]\n")
set(expected_stringindexnegative "String index, slice or size out of range")
set(expected_stringindexupper "String index, slice or size out of range")
set(expected_stringsliceclosed "String index, slice or size out of range")
set(expected_stringstepzero "Range step must be positive")
list(APPEND cases arrayinsertnegative arrayinsertupper arrayinsertingupper)
set(arrayinsertnegative "var a = [[1]]\na.insert([2], at: -1)\n")
set(arrayinsertupper "var a = [[1]]\na.insert([2], at: 2)\n")
set(arrayinsertingupper "var a = [[1]]\na.insert([2], at: 2)\n")
set(arrayremovenegative "var a = [[1]]\na.remove(at: -1)\n")
set(arrayremoveupper "var a = [[1]]\na.remove(at: 1)\n")
set(arrayremoveempty "var empty: [[Int64]] = []\nempty.remove(at: 0)\n")
set(arrayiterationerror "for row in [[1, 2], [3]]:\n    let copy = [row]\n    assert(false)\n")
set(arraybudget "struct Node:\n    var children: [Node]\nvar root = Node([])\nfor i in 0..<1000000:\n    root = Node([root])\n")
set(arraypartial "func f(i: Int64) -> [Int64]:\n    let a = [1, 2]\n    assert(i == 0)\n    return a\nlet a = [f(0), f(1)]\n")
set(arraynegative "let a = [1, 2]\nprint(a[-1])\n")
set(arrayupper "let a = [1, 2]\nprint(a[2])\n")
set(arrayreturnerror "func f() -> [Int64]:\n    let a = [1, 2]\n    assert(false)\n    return a\nlet a = f()\n")
configure_file("${SOURCE_DIR}/tests/fixtures/language/native.phys" "${project}/native.phys" COPYONLY)
file(READ "${SOURCE_DIR}/tests/fixtures/language/records.phys" records)
file(READ "${SOURCE_DIR}/tests/fixtures/language/enums.phys" enums)
file(READ "${SOURCE_DIR}/tests/fixtures/language/conversions.phys" conversions)
set(conversionupper "print(Int64(9223372036854775808.0))\n")
set(conversionlower "print(Int64(-9223372036854777856.0))\n")
set(conversionroundtrip "print(Int64(Float64(9223372036854775807)))\n")
list(APPEND cases textintinvalid textintoverflow textfloatinvalid textfloatoverflow)
set(textintinvalid "let x = Int64(\"1.2\")\n")
set(textintoverflow "let x = Int64(\"9223372036854775808\")\n")
set(textfloatinvalid "let x = Float64(\"NaN\")\n")
set(textfloatoverflow "let x = Float64(\"1e9999\")\n")
set(vectorzero "let v = Vec3(1, 2, 3) / 0\n")
set(vectoroverflow "let v = Vec2(1e308, 0) * 2\n")
set(vectorlength "let v = (Vec3(1.7e308, 1.7e308, 1.7e308)).length()\n")
set(vectordot "let v = (Vec3(1e308, 0, 0)).dot(Vec3(2, 0, 0))\n")
list(APPEND cases vector4zero vector4overflow vector4length vector4dot phase_space)
set(vector4zero "let v = Vec4(1, 2, 3, 4) / 0\n")
set(vector4overflow "let v = Vec4(0, 0, 0, 1e308) * 2\n")
set(vector4length "let v = (Vec4(1e308, 1e308, 1e308, 1e308)).length()\n")
set(vector4dot "let v = (Vec4(0, 0, 0, 1e308)).dot(Vec4(0, 0, 0, 2))\n")
file(READ "${SOURCE_DIR}/examples/language/phase_space.phys" phase_space)
list(APPEND cases rotation_path quatzero quatstartzero quatendzero quatfractionlow quatfractionhigh quatoverflow)
file(READ "${SOURCE_DIR}/examples/language/rotation_path.phys" rotation_path)
set(quatzero "let q = (Quat(0, 0, 0, 0)).normalized()\n")
set(quatstartzero "let q = (Quat(0, 0, 0, 0)).slerp(Quat(0, 0, 0, 1), 0.5)\n")
set(quatendzero "let q = (Quat(0, 0, 0, 1)).slerp(Quat(0, 0, 0, 0), 0.5)\n")
set(quatfractionlow "let q = (Quat(0, 0, 0, 1)).slerp(Quat(0, 0, 0, 1), -0.1)\n")
set(quatfractionhigh "let q = (Quat(0, 0, 0, 1)).slerp(Quat(0, 0, 0, 1), 1.1)\n")
set(quatoverflow "let q = (Quat(0, 0, 0, 1e308)).multiplied(Quat(0, 0, 0, 2))\n")
list(APPEND cases springinvalid springsingular draginvalid buoyancyinvalid forceoverflow)
list(APPEND cases compoundoverflow compoundglobal)
set(compoundoverflow "var x = 9223372036854775807\nx += 1\n")
set(compoundglobal "func f():\n    later += 1\nf()\nvar later = 1\n")
set(springinvalid "let v = springForce(Vec3(1, 0, 0), Vec3(0, 0, 0), Vec3(0, 0, 0), Vec3(0, 0, 0), -1, 1, 0)\n")
set(springsingular "let v = springForce(Vec3(0, 0, 0), Vec3(0, 0, 0), Vec3(0, 0, 0), Vec3(0, 0, 0), 1, 1, 0)\n")
set(draginvalid "let v = stokesDrag(Vec3(1, 0, 0), 1, 0)\n")
set(buoyancyinvalid "let v = buoyancyForce(-1, 1, Vec3(0, -1, 0))\n")
set(forceoverflow "let v = buoyancyForce(1e308, 1e308, Vec3(0, -10, 0))\n")
file(READ "${SOURCE_DIR}/tests/fixtures/language/sdk.phys" sdk)
set(uniterror "let m = Unit(1, 0, 0, 0, 0, 0, 0, 1, \"m\")\nlet s = Unit(0, 0, 1, 0, 0, 0, 0, 1, \"s\")\nfunc dynamicUnit() -> Unit:\n    return s\nprint(m.convert(1, dynamicUnit()))\n")
set(domainerror "print(sqrt(-1))\n")
set(mathlogdomain "print(log(-1))\n")
set(mathpowdomain "print(pow(-1,0.5))\n")
set(mathexpoverflow "print(exp(1000))\n")
set(mathatan2zero "print(atan2(0,0))\n")
set(mathhypotoverflow "print(hypot(1.7e308,1.7e308))\n")
set(add "let x = 9223372036854775807\nprint(x + 1)\n")
set(sub "let x = -9223372036854775808\nprint(x - 1)\n")
set(mul "let x = -9223372036854775808\nprint(x * -1)\n")
set(neg "let x = -9223372036854775808\nprint(-x)\n")
set(divzero "var x = 0\nprint(1 / x)\n")
set(divoverflow "let x = -9223372036854775808\nprint(x / -1)\n")
set(modzero "var x = 0\nprint(1 % x)\n")
set(floatzero "var x = 0.0\nprint(1.0 / x)\n")
set(floatoverflow "var x = 1e308\nprint(x * x)\n")
set(literal "print(1e999)\n")
set(globalread "func read() -> Int64:\n    return later\nlet early = read()\nlet later = 1\n")
set(globalwrite "func write():\n    later = 2\nwrite()\nvar later = 1\n")
set(fieldread "struct Value:\n    var x: Int64\nfunc read() -> Int64:\n    return later.x\nlet early = read()\nvar later = Value(1)\n")
set(fieldwrite "struct Value:\n    var x: Int64\nfunc write():\n    later.x = 2\nwrite()\nvar later = Value(1)\n")
set(recursion "func recurse():\n    recurse()\nrecurse()\n")
set(assertion "assert(false)\n")
set(assertionmessage "let reason = \"trajectory \" + \"diverged\"\nassert(false, message: reason)\n")
string(REPEAT "x" 70000 longtext)
string(REPEAT "0" 70000 longzero)
set(longliteral "let text = \"${longtext}\"\nassert(text == \"${longtext}\")\nlet n: Float64 = ${longzero}1\nassert(n == 1.0)\n")
set(project_text "cmake_minimum_required(VERSION 3.24)\nproject(GeneratedLanguage C)\nset(CMAKE_C_STANDARD 17)\nset(CMAKE_C_STANDARD_REQUIRED ON)\nset(CMAKE_C_EXTENSIONS OFF)\n")
string(APPEND project_text "include_directories(\"${SOURCE_DIR}/include\")\n")
string(APPEND project_text "include(\"${SOURCE_DIR}/cmake/PhysimLanguage.cmake\")\nset(PHYSIM_COMPILER \"${COMPILER}\")\n")
foreach(case IN LISTS cases)
  if(NOT case STREQUAL "native")
    file(WRITE "${project}/${case}.phys" "${${case}}")
  endif()
  execute_process(COMMAND "${COMPILER}" --emit-c "${project}/${case}.phys"
    RESULT_VARIABLE result OUTPUT_FILE "${project}/${case}.c" ERROR_VARIABLE error TIMEOUT 15)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "C emission failed for ${case}: ${result}\n${error}")
  endif()
  if(case MATCHES "^array" OR case MATCHES "^optional" OR case MATCHES "^ode" OR
     case STREQUAL "particles" OR
     case STREQUAL "switch_wildcards" OR case STREQUAL "linear_solve" OR
     case STREQUAL "linearupper")
    # Check the allocator balance even when generated main exits through a trap.
    file(READ "${project}/${case}.c" generated)
    file(WRITE "${project}/${case}.c" "#define main ps_test_main\n${generated}\n#undef main\nstatic void ps_test_balance(void) { if (psmemory.live_bytes) _Exit(99); }\nint main(void) { if (atexit(ps_test_balance)) return 98; return ps_test_main(); }\n")
  endif()
  if(case STREQUAL "native")
    string(APPEND project_text "physim_add_program(native native.phys)\n")
  else()
    string(APPEND project_text "add_executable(${case} ${case}.c)\n")
    string(APPEND project_text "target_link_libraries(${case} PRIVATE physim_language_sdk)\n")
  endif()
  string(APPEND project_text "set_target_properties(${case} PROPERTIES RUNTIME_OUTPUT_DIRECTORY \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_DEBUG \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_RELEASE \"${WORK}/bin\" RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO \"${WORK}/bin\")\n")
  if(NOT WIN32)
    string(APPEND project_text "target_link_libraries(${case} PRIVATE m)\n")
  endif()
endforeach()
file(WRITE "${project}/source_map_probe.phys" "func mapped():\n    let value = 1\nmapped()\n")
execute_process(COMMAND "${COMPILER}" --emit-c "${project}/source_map_probe.phys"
  RESULT_VARIABLE result OUTPUT_VARIABLE mapped_c ERROR_VARIABLE error TIMEOUT 15)
if(NOT result EQUAL 0 OR NOT mapped_c MATCHES "#line 1 " OR
   NOT mapped_c MATCHES "#line 2 " OR NOT error STREQUAL "")
  message(FATAL_ERROR "Source line emission failed: ${result}\n${error}")
endif()
string(FIND "${mapped_c}" "#line 1 " marker)
string(SUBSTRING "${mapped_c}" ${marker} -1 after_marker)
string(FIND "${after_marker}" "\n" line_end)
math(EXPR insertion "${marker} + ${line_end} + 1")
string(SUBSTRING "${mapped_c}" 0 ${insertion} before_error)
string(SUBSTRING "${mapped_c}" ${insertion} -1 after_error)
file(WRITE "${project}/source_map_probe.c"
  "${before_error}#error PHYSIM_SOURCE_MAP_PROBE\n${after_error}")
string(APPEND project_text "add_executable(source_map_probe EXCLUDE_FROM_ALL source_map_probe.c)\n")
file(WRITE "${project}/CMakeLists.txt" "${project_text}")
set(options -G "${GENERATOR}" "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_C_FLAGS=${C_FLAGS}")
if(DEFINED MAKE_PROGRAM AND NOT MAKE_PROGRAM STREQUAL "")
  list(APPEND options "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}")
endif()
if(NOT CONFIG)
  set(CONFIG Debug)
endif()
list(APPEND options "-DCMAKE_BUILD_TYPE=${CONFIG}")
# ASan/MSVC cannot link incrementally.
if(WIN32 AND C_FLAGS MATCHES "/fsanitize=address")
  list(APPEND options "-DCMAKE_EXE_LINKER_FLAGS=/INCREMENTAL:NO")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${project}" -B "${WORK}/build" ${options}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Generated project configure failed: ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}" --parallel 4
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 180)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native compilation failed (${result}): ${output}\n${error}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}"
  --target source_map_probe RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
  TIMEOUT 60)
if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "source_map_probe.phys" OR
   NOT "${output}${error}" MATCHES "PHYSIM_SOURCE_MAP_PROBE")
  message(FATAL_ERROR "Native compiler lost Physim source location: ${result}\n${output}\n${error}")
endif()
set(expected_add "addition overflow")
set(expected_arraynegative "Array index")
set(expected_arrayupper "Array index")
set(expected_arrayreturnerror "Assertion failed")
set(expected_arraypartial "Assertion failed")
set(expected_arrayiterationerror "Assertion failed")
set(expected_arraymethoderror "Assertion failed")
set(expected_arraymethodrecursion "recursion limit")
set(expected_arrayappenderror "Assertion failed")
set(expected_arrayappendindex "Array index")
set(expected_arrayremovemethod "Array index")
foreach(case arrayslicenegative arrayslicereversed arraysliceupper arraysliceclosed
             arrayslicemax arraysliceempty)
  set(expected_${case} "Array index, size or ownership limit exceeded")
endforeach()
foreach(case arrayrangereversed arrayrangeupper arrayrangeclosed arrayrangeempty)
  set(expected_${case} "Array index, size or ownership limit exceeded")
endforeach()
foreach(case arrayopenupper arrayopenlower arrayopenclosed arrayopenassign)
  set(expected_${case} "Array index, size or ownership limit exceeded")
endforeach()
set(expected_arrayrangeerror "Assertion failed")
set(expected_strideloopzero "Range step must not be zero")
foreach(case strideslicezero stridescatterzero)
  set(expected_${case} "Range step must be positive")
endforeach()
set(expected_stridescattercount "Array index, size or ownership limit exceeded")
set(expected_arraysliceerror "Assertion failed")
set(expected_arrayremovenegative "Array index, size or ownership limit exceeded")
set(expected_arrayremoveupper "Array index, size or ownership limit exceeded")
set(expected_arrayremoveempty "Array index, size or ownership limit exceeded")
foreach(case arrayinsertnegative arrayinsertupper arrayinsertingupper)
  set(expected_${case} "Array index, size or ownership limit exceeded")
endforeach()
set(expected_arraybudget "Array memory budget")
set(expected_sub "subtraction overflow")
set(expected_mul "multiplication overflow")
set(expected_neg "negation overflow")
set(expected_bitshiftnegative "Bit shift count must be between 0 and 63")
set(expected_bitshiftlarge "Bit shift count must be between 0 and 63")
set(expected_divzero "Division by zero")
set(expected_divoverflow "division overflow")
set(expected_modzero "Remainder by zero")
set(expected_floatzero "Division by zero")
set(expected_floatoverflow "Non-finite Float64")
set(expected_literal "Non-finite Float64")
set(expected_globalread "Global used before initialization")
set(expected_globalwrite "Global used before initialization")
set(expected_fieldread "Global used before initialization")
set(expected_fieldwrite "Global used before initialization")
set(expected_recursion "recursion limit")
set(expected_assertion "Assertion failed")
set(expected_assertionmessage "trajectory diverged")
set(expected_uniterror "Incompatible unit conversion")
set(expected_domainerror "Non-finite Float64")
set(expected_mathlogdomain "Non-finite Float64")
set(expected_mathpowdomain "Non-finite Float64")
set(expected_mathexpoverflow "Non-finite Float64")
set(expected_mathatan2zero "atan2 requires a nonzero x or y")
set(expected_mathhypotoverflow "Non-finite Float64")
set(expected_clampinverted "Clamp lower bound exceeds upper bound")
set(expected_beziernegative "Bezier parameter must be between 0 and 1")
set(expected_bezierupper "Bezier parameter must be between 0 and 1")
set(expected_beziertangentoverflow "Bezier evaluation exceeds numeric range")
set(expected_linearsingular "Linear system is singular")
set(expected_linearshape "Linear solve requires an n by n matrix")
set(expected_linearempty "Linear solve requires an n by n matrix")
set(expected_linearupper "Linear solve requires an n by n matrix")
set(expected_lineartolerance "Invalid linear solve values or pivot tolerance")
set(expected_linearnumeric "Linear solve exceeds numeric range")
set(expected_scalarbracket "Invalid bisection bracket or tolerances")
set(expected_scalarlimit "Scalar search did not converge")
set(expected_scalariterations "Scalar search requires 1 to 100000 iterations")
set(expected_scalarreportbracket "Invalid bisection bracket or tolerances")
set(expected_scalarreportcallback "Assertion failed")
set(expected_odeempty "ODE step requires 1 to 32 state values")
set(expected_odeupper "ODE step requires 1 to 32 state values")
set(expected_odebadstep "Invalid ODE state, time or positive step size")
set(expected_odeshape "ODE derivative has wrong state dimension")
set(expected_odeinner "Assertion failed")
set(expected_odenumeric "ODE step produced a non-finite value")
set(expected_rk45empty "RK45 integration requires 1 to 32 state values")
set(expected_rk45upper "RK45 integration requires 1 to 32 state values")
set(expected_rk45budget "RK45 trial step budget is out of range")
set(expected_rk45badoptions "Invalid integration argument or option")
set(expected_rk45badsteps "Invalid integration argument or option")
set(expected_rk45zerostep "Invalid integration argument or option")
set(expected_rk45limit "Trial step budget exhausted")
set(expected_rk45shape "ODE derivative has wrong state dimension")
set(expected_rk45inner "Assertion failed")
set(expected_rk45toleranceshape "RK45 component tolerances require one value per state component")
set(expected_rk45tolerancevalue "Invalid component absolute tolerance")
set(expected_rk45reportbudget "RK45 trial step budget is out of range")
set(expected_rk45reportcallback "Assertion failed")
set(expected_rk45reporttoleranceshape "RK45 component tolerances require one value per state component")
set(expected_rk45reporttolerancevalue "Invalid component absolute tolerance")
set(expected_verletempty "Verlet phase requires paired position and velocity values")
set(expected_verletodd "Verlet phase requires paired position and velocity values")
set(expected_verletupper "Verlet phase requires paired position and velocity values")
set(expected_verletbadstep "Invalid Verlet phase, time or nonzero step size")
set(expected_verletshape "Verlet acceleration has wrong state dimension")
set(expected_verletinner "Assertion failed")
set(expected_conversionupper "conversion out of range")
set(expected_conversionlower "conversion out of range")
set(expected_conversionroundtrip "conversion out of range")
set(expected_textintinvalid "Invalid Int64 text")
set(expected_textintoverflow "Int64 text out of range")
set(expected_textfloatinvalid "Invalid Float64 text")
set(expected_textfloatoverflow "Float64 text out of range")
set(expected_vectorzero "Division by zero")
set(expected_vectoroverflow "Non-finite Float64")
set(expected_vectorlength "Non-finite Float64")
set(expected_vectordot "Non-finite Float64")
set(expected_vector4zero "Division by zero")
set(expected_vector4overflow "Non-finite Float64")
set(expected_vector4length "Non-finite Float64")
set(expected_vector4dot "Non-finite Float64")
set(expected_quatzero "finite nonzero quaternion")
set(expected_quatstartzero "finite nonzero quaternion")
set(expected_quatendzero "finite nonzero quaternion")
set(expected_quatfractionlow "interpolation fraction")
set(expected_quatfractionhigh "interpolation fraction")
set(expected_quatoverflow "Non-finite Float64")
set(expected_springinvalid "Invalid force parameters")
set(expected_springsingular "Spring endpoints coincide")
set(expected_draginvalid "Invalid force parameters")
set(expected_buoyancyinvalid "Invalid force parameters")
set(expected_forceoverflow "Non-finite force result")
set(expected_compoundoverflow "addition overflow")
set(expected_compoundglobal "Global used before initialization")
if(WIN32)
  set(extension .exe)
endif()
foreach(case IN LISTS cases)
  execute_process(COMMAND "${WORK}/bin/${case}${extension}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  if(case STREQUAL "native")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "native checks passed\ntrue\n42\n0.5\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Native reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "optionalbindings")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "conditional binding checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Conditional binding or memory balance failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "optionalvalues")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "optional value checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Optional reference or memory balance failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "conversions")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "conversion checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Conversion reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "arrays")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "array checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Array reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "enums")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "enum checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Enum reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "sdk")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "sdk checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "SDK reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "records")
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "record checks passed\n" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Record reference failed: ${result}\n${output}\n${error}")
    endif()
  elseif(case STREQUAL "scalar_report" OR case STREQUAL "rk45_report" OR case STREQUAL "verlet_step" OR case STREQUAL "rk45_integrate" OR case STREQUAL "ode_step" OR case STREQUAL "scalar_search" OR case STREQUAL "linear_solve" OR case STREQUAL "bezier_curve" OR case STREQUAL "switch_wildcards" OR case STREQUAL "numeric_bounds" OR case STREQUAL "unicode_identifiers" OR case STREQUAL "enum_methods" OR case STREQUAL "bitwise" OR case STREQUAL "longliteral" OR case STREQUAL "phase_space" OR case STREQUAL "rotation_path" OR case STREQUAL "particles" OR case STREQUAL "arraymethods" OR case STREQUAL "mutating" OR case STREQUAL "units" OR case STREQUAL "sensors")
    if(NOT result EQUAL 0 OR NOT output STREQUAL "" OR NOT error STREQUAL "")
      message(FATAL_ERROR "Large literals failed: ${result}\n${error}")
    endif()
  elseif(NOT result EQUAL 70 OR NOT error MATCHES "${case}.phys:[0-9]+:[0-9]+: runtime error:.*${expected_${case}}")
    message(FATAL_ERROR "Runtime guard failed for ${case}: ${result}\n${output}\n${error}")
  endif()
endforeach()
file(SHA256 "${WORK}/build/native.physim.c" previous_generated)
file(WRITE "${project}/native.phys" "let immutable = 1\nimmutable = 2\n")
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config "${CONFIG}" --target native
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
file(SHA256 "${WORK}/build/native.physim.c" failed_generated)
configure_file("${SOURCE_DIR}/tests/fixtures/language/native.phys" "${project}/native.phys" COPYONLY)
if(result EQUAL 0 OR NOT previous_generated STREQUAL failed_generated OR
   EXISTS "${WORK}/build/native.physim.c.tmp")
  message(FATAL_ERROR "Failed source must stop build and preserve last complete generated file")
endif()
message(STATUS "Native C17: source-order evaluation, recursion, loops, strings, arithmetic and runtime diagnostics passed")
