# Compatibility entry point for the remaining CTest build. The direct runner
# consumes this same corpus without reading or executing any CMake files.
foreach(required COMPILER WORK PHYSIM_LANGUAGE_CASE_GROUP)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_language_cases.json" corpus)
string(JSON version GET "${corpus}" format)
if(NOT version EQUAL 1)
  message(FATAL_ERROR "Unsupported native language test corpus")
endif()

function(physim_language_expect record result output diagnostic)
  string(JSON expected_exit ERROR_VARIABLE absent GET "${record}" exit_code)
  if(absent)
    set(expected_exit 0)
  endif()
  if(NOT "${result}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Unexpected language exit: ${result}; expected ${expected_exit}\n${diagnostic}")
  endif()
  foreach(field stdout stderr stderr_pattern)
    string(JSON expected ERROR_VARIABLE absent GET "${record}" ${field})
    if(absent)
      continue()
    endif()
    if(field STREQUAL "stdout")
      set(actual "${output}")
    else()
      set(actual "${diagnostic}")
    endif()
    if(field STREQUAL "stderr_pattern")
      if(NOT actual MATCHES "${expected}")
        message(FATAL_ERROR "Missing language diagnostic: ${expected}\n${diagnostic}")
      endif()
    elseif(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Unexpected language ${field}: ${actual}")
    endif()
  endforeach()
  string(JSON count ERROR_VARIABLE absent LENGTH "${record}" stdout_patterns)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON expected GET "${record}" stdout_patterns ${index})
      if(NOT output MATCHES "${expected}")
        message(FATAL_ERROR "Missing generated output pattern: ${expected}")
      endif()
    endforeach()
  endif()
endfunction()

# Legacy CTest already builds these programs; share their runtime expectations
# with the direct compiler path as well as the diagnostic cases below.
function(physim_check_language_program name program)
  if(NOT EXISTS "${program}")
    message(FATAL_ERROR "Missing language program: ${program}")
  endif()
  string(JSON count LENGTH "${corpus}" programs)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON record GET "${corpus}" programs ${index})
    string(JSON candidate GET "${record}" name)
    if(candidate STREQUAL name)
      execute_process(COMMAND "${program}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 15)
      physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "Unknown language program: ${name}")
endfunction()

string(JSON group_count LENGTH "${corpus}" groups)
math(EXPR last_group "${group_count} - 1")
set(found FALSE)
foreach(group RANGE ${last_group})
  string(JSON name GET "${corpus}" groups ${group} name)
  if(NOT name STREQUAL PHYSIM_LANGUAGE_CASE_GROUP)
    continue()
  endif()
  set(found TRUE)
  string(JSON count LENGTH "${corpus}" groups ${group} checks)
  if(count LESS 1)
    message(FATAL_ERROR "Language test group has no checks: ${name}")
  endif()
  math(EXPR last "${count} - 1")
  file(MAKE_DIRECTORY "${WORK}")
  foreach(index RANGE ${last})
    string(JSON record GET "${corpus}" groups ${group} checks ${index})
    string(JSON case_name GET "${record}" name)
    string(JSON source GET "${record}" source)
    string(JSON mode ERROR_VARIABLE absent GET "${record}" mode)
    if(absent)
      set(mode --check)
    endif()
    # file(WRITE) expands LF to CRLF on Windows. Avoid creating CRCRLF when
    # the shared fixture already explicitly contains Windows line endings.
    if(WIN32)
      string(REPLACE "\r\n" "\n" source "${source}")
    endif()
    file(WRITE "${WORK}/${case_name}.phys" "${source}")
    execute_process(COMMAND "${COMPILER}" "${mode}" "${WORK}/${case_name}.phys"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 15)
    physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
  endforeach()
endforeach()
if(NOT found)
  message(FATAL_ERROR "Unknown native language test group: ${PHYSIM_LANGUAGE_CASE_GROUP}")
endif()
