if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Missing source root")
endif()
file(READ "${ROOT}/docs/language-analysis-tutorial.md" tutorial)
file(READ "${ROOT}/examples/language/analysis_batch_endpoints.phys" source)
string(REPLACE "\r\n" "\n" tutorial "${tutorial}")
string(REPLACE "\r" "\n" tutorial "${tutorial}")
string(REPLACE "\r\n" "\n" source "${source}")
string(REPLACE "\r" "\n" source "${source}")
string(FIND "${tutorial}" "```physim\n${source}```" position)
if(position LESS 0)
  message(FATAL_ERROR "The batch-analysis tutorial differs from its tested source")
endif()
