# Execute prebuilt modules with the same expectations as the direct test runner.
include("${CMAKE_CURRENT_LIST_DIR}/language_corpus.cmake")

function(physim_language_workflow requested parent_work)
  string(JSON count LENGTH "${corpus}" workflows)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON workflow GET "${corpus}" workflows ${index})
    string(JSON name GET "${workflow}" name)
    if(NOT name STREQUAL requested)
      continue()
    endif()
    string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
    set(work "${parent_work}/run-${suffix}")
    file(MAKE_DIRECTORY "${work}")
    string(JSON module_count LENGTH "${workflow}" modules)
    math(EXPR last_module "${module_count} - 1")
    foreach(module RANGE ${last_module})
      string(JSON module_name GET "${workflow}" modules ${module} name)
      if(NOT EXISTS "${PHYSIM_MODULE_${module_name}}")
        message(FATAL_ERROR "Missing workflow module: ${module_name}")
      endif()
    endforeach()
    string(JSON count LENGTH "${workflow}" steps)
    math(EXPR last_step "${count} - 1")
    foreach(step RANGE ${last_step})
      string(JSON record GET "${workflow}" steps ${step})
      string(JSON program GET "${record}" program)
      if(program STREQUAL "physim-runner")
        set(command "${EXPERIMENT_RUNNER}")
      elseif(program STREQUAL "physim-analysis-runner")
        set(command "${ANALYSIS_RUNNER}")
      else()
        message(FATAL_ERROR "Unknown workflow program: ${program}")
      endif()
      string(JSON count LENGTH "${record}" arguments)
      math(EXPR last_arg "${count} - 1")
      foreach(arg RANGE ${last_arg})
        string(JSON value GET "${record}" arguments ${arg})
        foreach(module RANGE ${last_module})
          string(JSON module_name GET "${workflow}" modules ${module} name)
          string(REPLACE "{${module_name}}" "${PHYSIM_MODULE_${module_name}}" value "${value}")
        endforeach()
        string(REPLACE "{work}" "${work}" value "${value}")
        list(APPEND command "${value}")
      endforeach()
      string(JSON timeout GET "${record}" timeout)
      execute_process(COMMAND ${command} WORKING_DIRECTORY "${work}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT ${timeout})
      physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
      foreach(field files absent_files file_contents)
        string(JSON count ERROR_VARIABLE absent LENGTH "${record}" ${field})
        if(absent OR count EQUAL 0)
          continue()
        endif()
        math(EXPR last_file "${count} - 1")
        foreach(file RANGE ${last_file})
          if(field STREQUAL "file_contents")
            string(JSON filename MEMBER "${record}" file_contents ${file})
          else()
            string(JSON filename GET "${record}" ${field} ${file})
          endif()
          if(field STREQUAL "absent_files")
            if(EXISTS "${work}/${filename}")
              message(FATAL_ERROR "Rejected operation created an output: ${filename}")
            endif()
          elseif(NOT EXISTS "${work}/${filename}" OR IS_DIRECTORY "${work}/${filename}")
            message(FATAL_ERROR "Missing workflow output: ${filename}")
          elseif(field STREQUAL "file_contents")
            file(READ "${work}/${filename}" actual)
            string(REPLACE "\r\n" "\n" actual "${actual}")
            string(JSON expected GET "${record}" file_contents "${filename}")
            if(NOT actual STREQUAL expected)
              message(FATAL_ERROR "Workflow output content did not match: ${filename}\n${actual}")
            endif()
          endif()
        endforeach()
      endforeach()
    endforeach()
    return()
  endforeach()
  message(FATAL_ERROR "Missing language workflow: ${requested}")
endfunction()
