foreach(required COMPILER WORK PROGRAM)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}")
function(reject name source expected)
  file(WRITE "${WORK}/${name}.phys" "${source}")
  execute_process(COMMAND "${COMPILER}" --check "${WORK}/${name}.phys"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic TIMEOUT 15)
  if(NOT result EQUAL 1 OR NOT diagnostic MATCHES "${expected}")
    message(FATAL_ERROR "${name} was not rejected: ${result}\n${diagnostic}")
  endif()
endfunction()
reject(missing_count "let values = Array(repeating: 1)\n" "Array\\(repeating:count:\\) expects a value and Int64 count")
reject(wrong_label "let values = Array(repeating: 1, times: 2)\n" "Array\\(repeating:count:\\) expects a value and Int64 count")
reject(wrong_type "let values = Array(repeating: 1, count: true)\n" "Expression type does not match required type")
reject(old_method "let values = [1].repeated(count: 2)\n" "Unknown method for this receiver type")
execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result
  ERROR_VARIABLE diagnostic TIMEOUT 15)
if(result EQUAL 0 OR NOT diagnostic MATCHES "array_repeated_negative.phys:1:[0-9]+: runtime error: Array repetition count must be nonnegative")
  message(FATAL_ERROR "Negative repeat did not report its call site: ${result}\n${diagnostic}")
endif()
