# Compatibility entry point for the remaining CTest build. The direct runner
# consumes this same corpus without reading or executing any CMake files.
foreach(required COMPILER WORK PHYSIM_LANGUAGE_CASE_GROUP)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/language_corpus.cmake")
get_filename_component(corpus_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

string(JSON group_count LENGTH "${corpus}" groups)
math(EXPR last_group "${group_count} - 1")
set(found FALSE)
foreach(group RANGE ${last_group})
  string(JSON name GET "${corpus}" groups ${group} name)
  if(NOT name STREQUAL PHYSIM_LANGUAGE_CASE_GROUP)
    continue()
  endif()
  set(found TRUE)
  string(JSON count LENGTH "${corpus}" groups ${group} checks)
  if(count LESS 1)
    message(FATAL_ERROR "Language test group has no checks: ${name}")
  endif()
  math(EXPR last "${count} - 1")
  file(MAKE_DIRECTORY "${WORK}")
  foreach(index RANGE ${last})
    string(JSON record GET "${corpus}" groups ${group} checks ${index})
    string(JSON case_name GET "${record}" name)
    set(case_work "${WORK}/${case_name}")
    file(MAKE_DIRECTORY "${case_work}")
    string(JSON directory_count ERROR_VARIABLE absent LENGTH "${record}" directories)
    if(NOT absent AND directory_count GREATER 0)
      math(EXPR last_directory "${directory_count} - 1")
      foreach(directory_index RANGE ${last_directory})
        string(JSON directory GET "${record}" directories ${directory_index})
        file(MAKE_DIRECTORY "${case_work}/${directory}")
      endforeach()
    endif()
    string(JSON file_count ERROR_VARIABLE absent LENGTH "${record}" files)
    if(NOT absent AND file_count GREATER 0)
      math(EXPR last_file "${file_count} - 1")
      foreach(file_index RANGE ${last_file})
        string(JSON filename MEMBER "${record}" files ${file_index})
        string(JSON content GET "${record}" files "${filename}")
        file(WRITE "${case_work}/${filename}" "${content}")
      endforeach()
    endif()
    string(JSON entry ERROR_VARIABLE absent GET "${record}" entry)
    if(absent)
      set(entry "${case_name}.phys")
    endif()
    string(JSON source ERROR_VARIABLE missing_source GET "${record}" source)
    string(JSON source_file ERROR_VARIABLE absent GET "${record}" source_file)
    if(NOT absent)
      file(READ "${corpus_root}/${source_file}" source)
      set(missing_source FALSE)
    endif()
    string(JSON repeat ERROR_VARIABLE absent GET "${record}" repeat_source)
    if(NOT absent)
      string(JSON text GET "${repeat}" text)
      string(JSON count GET "${repeat}" count)
      string(REPEAT "${text}" ${count} source)
      set(missing_source FALSE)
    endif()
    # file(WRITE) expands LF to CRLF on Windows. Avoid creating CRCRLF when
    # the shared fixture already explicitly contains Windows line endings.
    if(NOT missing_source)
      if(WIN32)
        string(REPLACE "\r\n" "\n" source "${source}")
      endif()
      file(WRITE "${case_work}/${entry}" "${source}")
    endif()
    string(JSON argument_count ERROR_VARIABLE absent LENGTH "${record}" arguments)
    set(command "${COMPILER}")
    if(absent)
      string(JSON mode ERROR_VARIABLE absent GET "${record}" mode)
      if(absent)
        set(mode --check)
      endif()
      list(APPEND command "${mode}" "${case_work}/${entry}")
    elseif(argument_count GREATER 0)
      math(EXPR last_argument "${argument_count} - 1")
      foreach(argument_index RANGE ${last_argument})
        string(JSON argument GET "${record}" arguments ${argument_index})
        string(REPLACE "{root}" "${corpus_root}" argument "${argument}")
        string(REPLACE "{work}" "${case_work}" argument "${argument}")
        string(REPLACE "{entry}" "${case_work}/${entry}" argument "${argument}")
        list(APPEND command "${argument}")
      endforeach()
    endif()
    execute_process(COMMAND ${command}
      WORKING_DIRECTORY "${case_work}"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 15)
    physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
  endforeach()
endforeach()
if(NOT found)
  message(FATAL_ERROR "Unknown native language test group: ${PHYSIM_LANGUAGE_CASE_GROUP}")
endif()
