if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Missing source root")
endif()
file(READ "${ROOT}/docs/language-tutorial.md" tutorial)
string(REPLACE "\r\n" "\n" tutorial "${tutorial}")
string(REPLACE "\r" "\n" tutorial "${tutorial}")
foreach(part main analysis)
  file(READ "${ROOT}/examples/documentation/language_${part}.phys" source)
  string(REPLACE "\r\n" "\n" source "${source}")
  string(REPLACE "\r" "\n" source "${source}")
  string(FIND "${tutorial}" "```physim\n${source}```" position)
  if(position LESS 0)
    message(FATAL_ERROR "The ${part} tutorial code differs from its tested source")
  endif()
endforeach()
