foreach(required COMPILER WORK ABS_PROGRAM CLAMP_PROGRAM)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}")
function(reject name source expected)
  file(WRITE "${WORK}/${name}.phys" "${source}")
  execute_process(COMMAND "${COMPILER}" --check "${WORK}/${name}.phys"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic TIMEOUT 15)
  if(NOT result EQUAL 1 OR NOT diagnostic MATCHES "${expected}")
    message(FATAL_ERROR "${name} was not rejected: ${result}\n${diagnostic}")
  endif()
endfunction()
reject(wrong_type "let x = Int64.abs(1.5)\n" "Expression type does not match required type")
reject(missing_arg "let x = Int64.min(1)\n" "Missing library arguments")
reject(internal_name "let x = intAbs(-1)\n" "Unknown function or value is not callable")
reject(multiple_missing "let n = 2\nlet x = n.isMultiple()\n" "Int64.isMultiple expects one of: argument")
reject(multiple_label "let n = 2\nlet x = n.isMultiple(by: 1)\n" "Int64.isMultiple expects one of: argument")
reject(multiple_type "let n = 2\nlet x = n.isMultiple(of: 1.5)\n" "Expression type does not match required type")
reject(signum_argument "let n = 2\nlet x = n.signum(1)\n" "Int64.signum expects no arguments")
execute_process(COMMAND "${ABS_PROGRAM}" RESULT_VARIABLE result
  ERROR_VARIABLE diagnostic TIMEOUT 15)
if(result EQUAL 0 OR NOT diagnostic MATCHES
   "int_abs_overflow\\.phys:1:[0-9]+: runtime error: Int64 absolute value overflow")
  message(FATAL_ERROR "Int64.abs overflow was not diagnosed: ${result}\n${diagnostic}")
endif()
execute_process(COMMAND "${CLAMP_PROGRAM}" RESULT_VARIABLE result
  ERROR_VARIABLE diagnostic TIMEOUT 15)
if(result EQUAL 0 OR NOT diagnostic MATCHES
   "int_clamp_bounds\\.phys:1:[0-9]+: runtime error: Clamp lower bound exceeds upper bound")
  message(FATAL_ERROR "Int64.clamp bounds were not diagnosed: ${result}\n${diagnostic}")
endif()
