# Compatibility entry point for the remaining CTest build. The direct runner
# consumes this same corpus without reading or executing any CMake files.
foreach(required COMPILER WORK PHYSIM_LANGUAGE_CASE_GROUP)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_language_cases.json" corpus)
string(JSON version GET "${corpus}" format)
if(NOT version EQUAL 1)
  message(FATAL_ERROR "Unsupported native language test corpus")
endif()
string(JSON group_count LENGTH "${corpus}" groups)
math(EXPR last_group "${group_count} - 1")
set(found FALSE)
foreach(group RANGE ${last_group})
  string(JSON name GET "${corpus}" groups ${group} name)
  if(NOT name STREQUAL PHYSIM_LANGUAGE_CASE_GROUP)
    continue()
  endif()
  set(found TRUE)
  string(JSON count LENGTH "${corpus}" groups ${group} checks)
  if(count LESS 1)
    message(FATAL_ERROR "Language test group has no checks: ${name}")
  endif()
  math(EXPR last "${count} - 1")
  file(MAKE_DIRECTORY "${WORK}")
  foreach(index RANGE ${last})
    string(JSON case_name GET "${corpus}" groups ${group} checks ${index} name)
    string(JSON source GET "${corpus}" groups ${group} checks ${index} source)
    string(JSON expected GET "${corpus}" groups ${group} checks ${index} stderr_pattern)
    string(JSON expected_exit GET "${corpus}" groups ${group} checks ${index} exit_code)
    file(WRITE "${WORK}/${case_name}.phys" "${source}")
    execute_process(COMMAND "${COMPILER}" --check "${WORK}/${case_name}.phys"
      RESULT_VARIABLE result ERROR_VARIABLE diagnostic TIMEOUT 15)
    if(NOT result EQUAL expected_exit OR NOT diagnostic MATCHES "${expected}")
      message(FATAL_ERROR "${case_name} was not rejected as expected: ${result}\n${diagnostic}")
    endif()
  endforeach()
endforeach()
if(NOT found)
  message(FATAL_ERROR "Unknown native language test group: ${PHYSIM_LANGUAGE_CASE_GROUP}")
endif()
