foreach(required EXPERIMENT ANALYSIS EXPERIMENT_RUNNER ANALYSIS_RUNNER WORK)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
set(PHYSIM_MODULE_experiment "${EXPERIMENT}")
set(PHYSIM_MODULE_analysis "${ANALYSIS}")
include("${CMAKE_CURRENT_LIST_DIR}/check_language_workflow_corpus.cmake")
physim_language_workflow(generic_modes "${WORK}")
