include("${CMAKE_CURRENT_LIST_DIR}/language_corpus.cmake")
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_integration_cases.json" integration_corpus)
string(JSON count LENGTH "${integration_corpus}" tests)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  string(JSON record GET "${integration_corpus}" tests ${index})
  string(JSON name GET "${record}" name)
  if(NOT name STREQUAL CASE_NAME)
    continue()
  endif()
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
  set(work "${WORK}/run-${suffix}/files ä")
  file(MAKE_DIRECTORY "${work}")
  string(JSON target_count LENGTH "${record}" targets)
  math(EXPR target_last "${target_count} - 1")
  foreach(target_index RANGE ${target_last})
    string(JSON target GET "${record}" targets ${target_index})
    if(NOT EXISTS "${ARTIFACT_${target}}")
      message(FATAL_ERROR "Missing integration artifact: ${target}")
    endif()
  endforeach()
  string(JSON step_count LENGTH "${record}" steps)
  math(EXPR step_last "${step_count} - 1")
  foreach(step_index RANGE ${step_last})
    string(JSON step GET "${record}" steps ${step_index})
    string(JSON program GET "${step}" program)
    set(command "${ARTIFACT_${program}}")
    string(JSON arg_count LENGTH "${step}" arguments)
    if(arg_count GREATER 0)
      math(EXPR arg_last "${arg_count} - 1")
      foreach(arg RANGE ${arg_last})
        string(JSON value GET "${step}" arguments ${arg})
        foreach(target_index RANGE ${target_last})
          string(JSON target GET "${record}" targets ${target_index})
          string(REPLACE "{${target}}" "${ARTIFACT_${target}}" value "${value}")
        endforeach()
        string(REPLACE "{work}" "${work}" value "${value}")
        string(REPLACE "{root}" "${CMAKE_CURRENT_LIST_DIR}/.." value "${value}")
        list(APPEND command "${value}")
      endforeach()
    endif()
    string(JSON timeout GET "${step}" timeout)
    execute_process(COMMAND ${command} WORKING_DIRECTORY "${work}" TIMEOUT ${timeout}
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic)
    string(REPLACE "\r\n" "\n" output "${output}")
    string(REPLACE "\r\n" "\n" diagnostic "${diagnostic}")
    physim_language_expect("${step}" "${result}" "${output}" "${diagnostic}")
    foreach(field files absent_files)
      string(JSON file_count ERROR_VARIABLE absent LENGTH "${step}" ${field})
      if(absent OR file_count EQUAL 0)
        continue()
      endif()
      math(EXPR file_last "${file_count} - 1")
      foreach(file_index RANGE ${file_last})
        string(JSON filename GET "${step}" ${field} ${file_index})
        if(field STREQUAL "absent_files")
          if(EXISTS "${work}/${filename}")
            message(FATAL_ERROR "Rejected operation created an output: ${filename}")
          endif()
        elseif(NOT EXISTS "${work}/${filename}" OR IS_DIRECTORY "${work}/${filename}")
          message(FATAL_ERROR "Missing integration output: ${filename}")
        endif()
      endforeach()
    endforeach()
  endforeach()
  return()
endforeach()
message(FATAL_ERROR "Unknown integration test: ${CASE_NAME}")
