if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Missing source root")
endif()
file(READ "${ROOT}/docs/projectile-drag-tutorial.md" tutorial)
string(REPLACE "\r\n" "\n" tutorial "${tutorial}")
string(REPLACE "\r" "\n" tutorial "${tutorial}")
foreach(part c_main physim_main c_analysis physim_analysis)
  if(part STREQUAL "c_main")
    set(source_path "${ROOT}/examples/projectile/main.c")
    set(language c)
  elseif(part STREQUAL "physim_main")
    set(source_path "${ROOT}/examples/language/projectile_drag.phys")
    set(language physim)
  elseif(part STREQUAL "c_analysis")
    set(source_path "${ROOT}/examples/documentation/drag_analysis.c")
    set(language c)
  else()
    set(source_path "${ROOT}/examples/documentation/drag_analysis.phys")
    set(language physim)
  endif()
  file(READ "${source_path}" source)
  string(REPLACE "\r\n" "\n" source "${source}")
  string(REPLACE "\r" "\n" source "${source}")
  string(FIND "${tutorial}" "```${language}\n${source}```" position)
  if(position LESS 0)
    message(FATAL_ERROR "The ${part} tutorial code differs from ${source_path}")
  endif()
endforeach()
