foreach(required EXPERIMENT ANALYSIS EXPERIMENT_RUNNER ANALYSIS_RUNNER WORK)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/language_corpus.cmake")
string(JSON count LENGTH "${corpus}" workflows)
math(EXPR last "${count} - 1")
set(found FALSE)
foreach(index RANGE ${last})
  string(JSON workflow GET "${corpus}" workflows ${index})
  string(JSON name GET "${workflow}" name)
  if(NOT name STREQUAL "generic_modes")
    continue()
  endif()
  set(found TRUE)
  # A fresh directory rules out success from an earlier run's output files.
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
  set(work "${WORK}/run-${suffix}")
  file(MAKE_DIRECTORY "${work}")
  string(JSON count LENGTH "${workflow}" steps)
  math(EXPR last_step "${count} - 1")
  foreach(step RANGE ${last_step})
    string(JSON record GET "${workflow}" steps ${step})
    string(JSON program GET "${record}" program)
    if(program STREQUAL "physim-runner")
      set(command "${EXPERIMENT_RUNNER}")
    elseif(program STREQUAL "physim-analysis-runner")
      set(command "${ANALYSIS_RUNNER}")
    else()
      message(FATAL_ERROR "Unknown generic workflow program: ${program}")
    endif()
    string(JSON count LENGTH "${record}" arguments)
    math(EXPR last_arg "${count} - 1")
    foreach(arg RANGE ${last_arg})
      string(JSON value GET "${record}" arguments ${arg})
      string(REPLACE "{experiment}" "${EXPERIMENT}" value "${value}")
      string(REPLACE "{analysis}" "${ANALYSIS}" value "${value}")
      string(REPLACE "{work}" "${work}" value "${value}")
      list(APPEND command "${value}")
    endforeach()
    string(JSON timeout GET "${record}" timeout)
    execute_process(COMMAND ${command} WORKING_DIRECTORY "${work}"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT ${timeout})
    physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
    string(JSON count LENGTH "${record}" files)
    math(EXPR last_file "${count} - 1")
    foreach(file RANGE ${last_file})
      string(JSON filename GET "${record}" files ${file})
      if(NOT EXISTS "${work}/${filename}" OR IS_DIRECTORY "${work}/${filename}")
        message(FATAL_ERROR "Missing generic workflow output: ${filename}")
      endif()
    endforeach()
  endforeach()
endforeach()
if(NOT found)
  message(FATAL_ERROR "Missing generic_modes workflow in language corpus")
endif()
