foreach(required BATCH RUNNER EXPERIMENT VERIFY WORK)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}")
if(DEFINED FIXED)
  foreach(invalid "--param;gain=nan" "--param;gain=2;--param;gain=3"
                  "--param;initialSpeed=2")
    string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
    set(rejected "${WORK}/fixed-rejected-${suffix}")
    execute_process(COMMAND "${BATCH}" "${RUNNER}" "${EXPERIMENT}" "${rejected}"
      speed 3 1 0.005 42 --sweep initialSpeed=1:4 ${invalid}
      RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 20)
    if(result EQUAL 0 OR EXISTS "${rejected}")
      message(FATAL_ERROR "Invalid fixed override was accepted: ${invalid}")
    endif()
  endforeach()
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(output "${WORK}/study-${suffix}")
set(extra)
if(DEFINED FIXED)
  list(APPEND extra --param "gain=${FIXED}")
endif()
execute_process(COMMAND "${BATCH}" "${RUNNER}" "${EXPERIMENT}" "${output}"
  speed 3 1 0.005 42 --workers 2 --sweep initialSpeed=1:4 ${extra}
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Parameter sweep runner failed: ${result}\n${stdout}\n${stderr}")
endif()
execute_process(COMMAND "${VERIFY}" "${output}" ${FIXED}
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 20)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Parameter sweep verification failed: ${result}\n${stdout}\n${stderr}")
endif()
foreach(invalid "initialSpeed=1:1" "initialSpeed=nan:3" "bad.name=1:" "9bad=1:3")
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
  set(rejected "${WORK}/rejected-${suffix}")
  execute_process(COMMAND "${BATCH}" "${RUNNER}" "${EXPERIMENT}" "${rejected}"
    speed 3 1 0.005 42 --sweep ${invalid}
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 20)
  if(result EQUAL 0 OR EXISTS "${rejected}")
    message(FATAL_ERROR "Invalid sweep was accepted: ${invalid}")
  endif()
endforeach()
