foreach(required COMPILER WORK PROGRAM)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${WORK}")
function(reject name source expected)
  file(WRITE "${WORK}/${name}.phys" "${source}")
  execute_process(COMMAND "${COMPILER}" --check "${WORK}/${name}.phys"
    RESULT_VARIABLE result ERROR_VARIABLE diagnostic TIMEOUT 15)
  if(NOT result EQUAL 1 OR NOT diagnostic MATCHES "${expected}")
    message(FATAL_ERROR "${name} was not rejected: ${result}\n${diagnostic}")
  endif()
endfunction()
reject(missing_count "let text = String(repeating: \"a\")\n" "String\\(repeating:count:\\) expects")
reject(wrong_label "let text = String(repeating: \"a\", times: 2)\n" "String\\(repeating:count:\\) expects")
reject(wrong_type "let text = String(repeating: \"a\", count: true)\n" "Expression type does not match required type")
reject(wrong_repeating_type "let text = String(repeating: 3, count: 2)\n" "Expression type does not match required type")
reject(old_method_name "let text = \"a\".repeated(count: 2)\n" "Unknown method for this receiver type")
execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result
  ERROR_VARIABLE diagnostic TIMEOUT 15)
if(result EQUAL 0 OR NOT diagnostic MATCHES "string_repeated_negative.phys:1:[0-9]+: runtime error: String repetition count must be nonnegative")
  message(FATAL_ERROR "Negative repeat did not report its call site: ${result}\n${diagnostic}")
endif()
