string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(directory "${ROOT}-${stamp}-${nonce}")
execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" documents-build
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 130)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Document build: ${result}\n${output}\n${errors}")
endif()
file(READ "${directory}/project with spaces/helper.h" header)
file(READ "${directory}/project with spaces/main.c" source)
if(NOT header STREQUAL "#define DOCUMENT_TEST_VERSION 4\n" OR
   NOT source MATCHES "DOCUMENT_TEST_VERSION >= 2")
  message(FATAL_ERROR "Edited build inputs did not reach disk")
endif()
message(STATUS "Changes saved during native compilation and parameter discovery reject stale builds; fresh builds succeed")
