string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
foreach(mode restore discard conflict cancel corrupt reset late-corrupt revert)
  set(directory "${ROOT}-${stamp}-${nonce}-${mode}")
  execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" drafts-write
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 25)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Document draft writer: ${result}\n${output}\n${errors}")
  endif()
  file(GLOB sources RELATIVE "${directory}/workspace" "${directory}/workspace/*")
  list(LENGTH sources source_count)
  file(GLOB drafts "${directory}/app-data/document-drafts/*.draft")
  list(LENGTH drafts draft_count)
  if(NOT source_count EQUAL 2 OR NOT draft_count EQUAL 2)
    message(FATAL_ERROR "Autosaves must exist outside the source directory, one per document")
  endif()
  file(READ "${directory}/workspace/notes α.txt" original)
  file(READ "${directory}/workspace/second.txt" second)
  if(NOT original STREQUAL "original α\n" OR NOT second STREQUAL "second original\n")
    message(FATAL_ERROR "Autosave modified source files")
  endif()
  if(mode STREQUAL conflict)
    file(WRITE "${directory}/workspace/notes α.txt" "external α\n")
  elseif(mode STREQUAL corrupt OR mode STREQUAL reset)
    foreach(draft IN LISTS drafts)
      file(WRITE "${draft}" "damaged snapshot")
    endforeach()
  endif()
  execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" "drafts-${mode}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 25)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Document recovery ${mode}: ${result}\n${output}\n${errors}")
  endif()
  file(READ "${directory}/workspace/notes α.txt" actual)
  file(READ "${directory}/workspace/second.txt" actual_second)
  if(mode STREQUAL cancel)
    if(NOT actual STREQUAL original OR NOT actual_second STREQUAL second)
      message(FATAL_ERROR "Closing unresolved recovery changed the sources")
    endif()
    foreach(draft IN LISTS drafts)
      if(NOT EXISTS "${draft}")
        message(FATAL_ERROR "Closing unresolved recovery removed a draft")
      endif()
    endforeach()
  elseif(mode STREQUAL reset OR mode STREQUAL late-corrupt)
    file(GLOB remaining "${directory}/app-data/document-drafts/*.draft")
    list(LENGTH remaining remaining_count)
    if(mode STREQUAL reset)
      set(expected "still in editor\n")
      set(expected_second "${second}")
    else()
      set(expected "first draft β 2\n")
      set(expected_second "second draft γ\n")
    endif()
    if(NOT remaining_count EQUAL 1 OR NOT actual STREQUAL expected OR
       NOT actual_second STREQUAL expected_second)
      message(FATAL_ERROR "Reset must resume autosave for the chosen document only")
    endif()
    file(READ "${remaining}" untouched)
    if(NOT untouched STREQUAL "damaged snapshot")
      message(FATAL_ERROR "Reset damaged another document's recovery")
    endif()
  elseif(mode STREQUAL corrupt)
    foreach(draft IN LISTS drafts)
      file(READ "${draft}" damaged)
      if(NOT damaged STREQUAL "damaged snapshot")
        message(FATAL_ERROR "Corrupt recovery was overwritten")
      endif()
    endforeach()
    if(NOT actual STREQUAL "still in editor\n")
      message(FATAL_ERROR "Paused autosave must not prevent explicit normal source saving")
    endif()
  else()
    if(mode STREQUAL discard OR mode STREQUAL revert)
      if(NOT actual STREQUAL original)
        message(FATAL_ERROR "Discard changed source file")
      endif()
    elseif(NOT actual STREQUAL "first draft β 2\n")
      message(FATAL_ERROR "Recovered draft was not saved")
    endif()
    if(mode STREQUAL conflict)
      file(READ "${directory}/workspace/notes α.txt.bak" backup)
      if(NOT backup STREQUAL "external α\n")
        message(FATAL_ERROR "Confirmed recovery did not preserve external contents as backup")
      endif()
    endif()
    if(NOT actual_second STREQUAL "second draft γ\n")
      message(FATAL_ERROR "Second document did not recover independently")
    endif()
    file(GLOB remaining "${directory}/app-data/document-drafts/*.draft")
    if(remaining)
      message(FATAL_ERROR "Resolved drafts remain after save/discard")
    endif()
  endif()
endforeach()
message(STATUS "Document recovery: abrupt exit, isolated cache, two documents, restore, discard, conflicts, cancel and corruption passed")
