string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(directory "${ROOT}-${stamp}-${nonce}")
execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" documents
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 25)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Documents: ${result}\n${output}\n${errors}")
endif()
file(READ "${directory}/notes α.txt" saved)
file(READ "${directory}/notes α.txt.bak" backup)
file(READ "${directory}/second.txt" external)
if(NOT saved STREQUAL "Saved on close: γ\n" OR
   NOT backup STREQUAL "Text über SDL: β = 2\n" OR NOT external STREQUAL "external")
  message(FATAL_ERROR "Document save/discard/backup roundtrip did not preserve the expected contents")
endif()
message(STATUS "Document input, switching, save, conflict, close/reload choices and source routing passed")
