# Shared expectations for the legacy CTest entry points.
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_language_cases.json" corpus)
string(JSON version GET "${corpus}" format)
if(NOT version EQUAL 1)
  message(FATAL_ERROR "Unsupported native language test corpus")
endif()

function(physim_language_expect record result output diagnostic)
  string(JSON expected_exit ERROR_VARIABLE absent GET "${record}" exit_code)
  if(absent)
    set(expected_exit 0)
  endif()
  if(NOT "${result}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Unexpected language exit: ${result}; expected ${expected_exit}\n${diagnostic}")
  endif()
  foreach(field stdout stderr stderr_pattern)
    string(JSON expected ERROR_VARIABLE absent GET "${record}" ${field})
    if(absent)
      continue()
    endif()
    if(field STREQUAL "stdout")
      set(actual "${output}")
    else()
      set(actual "${diagnostic}")
    endif()
    if(field STREQUAL "stderr_pattern")
      if(NOT actual MATCHES "${expected}")
        message(FATAL_ERROR "Missing language diagnostic: ${expected}\n${diagnostic}")
      endif()
    elseif(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Unexpected language ${field}: ${actual}")
    endif()
  endforeach()
  string(JSON count ERROR_VARIABLE absent LENGTH "${record}" stdout_patterns)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON expected GET "${record}" stdout_patterns ${index})
      if(NOT output MATCHES "${expected}")
        message(FATAL_ERROR "Missing generated output pattern: ${expected}")
      endif()
    endforeach()
  endif()
  string(JSON count ERROR_VARIABLE absent LENGTH "${record}" stdout_captures)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON pattern GET "${record}" stdout_captures ${index} pattern)
      string(JSON expected GET "${record}" stdout_captures ${index} expected)
      string(REGEX MATCH "${pattern}" matched "${output}")
      if(NOT matched)
        message(FATAL_ERROR "Missing output capture: ${pattern}")
      endif()
      string(STRIP "${CMAKE_MATCH_1}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Unexpected first output capture: ${actual}; expected ${expected}")
      endif()
    endforeach()
  endif()
endfunction()

# Legacy CTest already builds these programs; share their runtime expectations
# with the direct compiler path as well as the diagnostic cases below.
function(physim_check_language_program name program)
  if(NOT EXISTS "${program}")
    message(FATAL_ERROR "Missing language program: ${program}")
  endif()
  string(JSON count LENGTH "${corpus}" programs)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON record GET "${corpus}" programs ${index})
    string(JSON candidate GET "${record}" name)
    if(candidate STREQUAL name)
      execute_process(COMMAND "${program}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 15)
      physim_language_expect("${record}" "${result}" "${output}" "${diagnostic}")
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "Unknown language program: ${name}")
endfunction()
