string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(mode --plot-test)
if(NOISE)
  set(mode --plot-test-noise)
endif()
execute_process(COMMAND "${APP}" ${mode} "${ROOT}-${stamp}-${nonce} ä"
  RESULT_VARIABLE result TIMEOUT 35)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Plot app workflow failed: ${result}")
endif()
