string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(directory "${ROOT}-${nonce} ä")
foreach(mode write read debug)
  execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" "project-settings-${mode}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
  if(NOT result EQUAL 0 OR NOT output MATCHES "PROJECT SETTINGS .*PASSED")
    message(FATAL_ERROR "Project settings ${mode}: ${result}\n${output}\n${errors}")
  endif()
  file(READ "${directory}/project/physim.project" project)
  if(NOT project MATCHES "simulation.dt=0.125" OR NOT project MATCHES "simulation.seed=18446744073709551615")
    message(FATAL_ERROR "Timestep or full-width seed not preserved")
  endif()
  if(mode STREQUAL write)
    if(NOT project MATCHES "profile=Release" OR NOT project MATCHES "parameter.friction=0.25")
      message(FATAL_ERROR "Release profile or parameters not saved on quit")
    endif()
    file(APPEND "${directory}/project/physim.project" "# extension preserved\ncustom.note=hello\n")
    file(SHA256 "${directory}/project/main.phys" source)
    file(SHA256 "${directory}/project/analysis.c" analysis)
  else()
    if(NOT project MATCHES "profile=Debug" OR NOT project MATCHES "parameter.friction=0.25" OR
       NOT project MATCHES "# extension preserved\ncustom.note=hello")
      message(FATAL_ERROR "Project settings or extension lost")
    endif()
    file(SHA256 "${directory}/project/main.phys" current_source)
    file(SHA256 "${directory}/project/analysis.c" current_analysis)
    if(NOT source STREQUAL current_source OR NOT analysis STREQUAL current_analysis)
      message(FATAL_ERROR "Saving project settings rewrote source files")
    endif()
  endif()
  if(EXISTS "${directory}/project/main.phys.bak" OR EXISTS "${directory}/project/analysis.c.bak" OR
     EXISTS "${directory}/project/CMakeLists.txt")
    message(FATAL_ERROR "Settings-only edit created unnecessary source backups or CMake files")
  endif()
endforeach()
file(READ "${directory}/project/build/Release/build.config" config)
if(NOT config MATCHES "profile=Release")
  message(FATAL_ERROR "Builder did not use the restored project profile")
endif()
message(STATUS "Project profile and parameters survive restart, release build and automatic saving; extensions and sources preserved")
