# Register existing CMake targets against the CMake-independent test catalog.
file(READ "${CMAKE_CURRENT_LIST_DIR}/native_integration_cases.json" integration_corpus)
string(JSON version GET "${integration_corpus}" format)
if(NOT version EQUAL 1)
  message(FATAL_ERROR "Unsupported integration test corpus")
endif()
string(JSON count LENGTH "${integration_corpus}" tests)
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  string(JSON record GET "${integration_corpus}" tests ${index})
  string(JSON name GET "${record}" name)
  string(JSON target_count LENGTH "${record}" targets)
  math(EXPR target_last "${target_count} - 1")
  set(options)
  foreach(target_index RANGE ${target_last})
    string(JSON target GET "${record}" targets ${target_index})
    if(NOT TARGET "${target}")
      message(FATAL_ERROR "Missing integration target: ${target}")
    endif()
    list(APPEND options "-DARTIFACT_${target}=$<TARGET_FILE:${target}>")
  endforeach()
  add_test(NAME "${name}" COMMAND "${CMAKE_COMMAND}"
    "-DCASE_NAME=${name}" "-DWORK=${CMAKE_BINARY_DIR}/native-integrations/${name}"
    ${options} -P "${CMAKE_CURRENT_LIST_DIR}/check_native_integration.cmake")
  string(JSON step_count LENGTH "${record}" steps)
  math(EXPR step_last "${step_count} - 1")
  set(total_timeout 10)
  foreach(step RANGE ${step_last})
    string(JSON timeout GET "${record}" steps ${step} timeout)
    math(EXPR total_timeout "${total_timeout} + ${timeout}")
  endforeach()
  set_tests_properties("${name}" PROPERTIES TIMEOUT ${total_timeout} LABELS native_integration)
endforeach()
