string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(directory "${ROOT}-${stamp}-${nonce} ä")
foreach(mode write read reset defaults maxwrite maxread corrupt)
  if(mode STREQUAL corrupt)
    file(WRITE "${directory}/preferences.bin" "damaged preferences")
  endif()
  execute_process(COMMAND "${APP}" --settings-test "${directory}" "${mode}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 25)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Settings ${mode}: ${result}\n${output}\n${errors}")
  endif()
endforeach()
file(READ "${directory}/preferences.bin" content)
if(NOT content STREQUAL "damaged preferences")
  message(FATAL_ERROR "Damaged preferences were overwritten")
endif()
message(STATUS "Settings controls, panel dragging, restart, cancellation, reset and corruption preservation passed")
