string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(directory "${ROOT}-${stamp}-${nonce} ä")
foreach(mode write read missing-addition missing-root forget empty write-folder read-folder corrupt)
  if(mode STREQUAL missing-addition)
    file(RENAME "${directory}/notes ä.txt" "${directory}/notes-moved.txt")
  elseif(mode STREQUAL missing-root)
    file(RENAME "${directory}/project" "${directory}/project-moved")
    file(SHA256 "${directory}/workspace.bin" before)
  elseif(mode STREQUAL corrupt)
    file(WRITE "${directory}/workspace.bin" "damaged workspace")
  endif()
  execute_process(COMMAND "${APP}" --workspace-state-test "${directory}" "${mode}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Workspace ${mode}: ${result}\n${output}\n${errors}")
  endif()
  if(mode STREQUAL missing-root)
    file(SHA256 "${directory}/workspace.bin" after)
    if(NOT before STREQUAL after)
      message(FATAL_ERROR "Missing root lost the saved workspace")
    endif()
  endif()
endforeach()
file(READ "${directory}/workspace.bin" content)
if(NOT content STREQUAL "damaged workspace")
  message(FATAL_ERROR "Damaged workspace was overwritten")
endif()
message(STATUS "Workspace restart, explicit UI restore, missing paths, forgetting and corruption preservation passed")
