"""Generate fixed Unicode identifier tables for the C17 Physim lexer.

Run with Python 3.12, whose bundled Unicode database is version 15.0.0.
The checked-in header removes a Python dependency from normal builds.
"""

from pathlib import Path
import unicodedata


if unicodedata.unidata_version != "15.0.0":
    raise SystemExit("Expected Unicode database 15.0.0")


def ranges(points):
    first = last = None
    for point in points:
        if first is None:
            first = last = point
        elif point == last + 1:
            last = point
        else:
            yield first, last
            first = last = point
    if first is not None:
        yield first, last


def table(name, points):
    lines = [f"static const ps_lang_unicode_range {name}[] = {{"]
    lines.extend(f"    {{0x{first:X}u, 0x{last:X}u}}," for first, last in ranges(points))
    lines.append("};")
    return "\n".join(lines)


scalars = range(0x80, 0x110000)
starts = (point for point in scalars if chr(point).isidentifier())
continues = (point for point in scalars if ("a" + chr(point)).isidentifier())
header = "\n".join(
    [
        "/* Generated by tools/generate-language-identifiers.py from Unicode 15.0.0. */",
        "#ifndef PS_LANGUAGE_UNICODE_IDENTIFIERS_H",
        "#define PS_LANGUAGE_UNICODE_IDENTIFIERS_H",
        "#include <stdint.h>",
        "typedef struct { uint32_t first, last; } ps_lang_unicode_range;",
        table("ps_lang_identifier_starts", starts),
        table("ps_lang_identifier_continues", continues),
        "#endif",
        "",
    ]
)
Path(__file__).resolve().parents[1].joinpath(
    "src", "language", "unicode_identifiers.h"
).write_text(header, encoding="ascii")
