cmake_minimum_required(VERSION 3.24)
if(NOT BUILD_DIR OR NOT IS_DIRECTORY "${BUILD_DIR}")
  message(FATAL_ERROR "Pass -DBUILD_DIR=<completed Physim build>")
endif()
if(NOT CONFIG)
  set(CONFIG Release)
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 token)
set(root "${BUILD_DIR}/SDK Test ä ${token}")
file(MAKE_DIRECTORY "${root}")
set(log "${root}/verification.log")
function(checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr TIMEOUT 300)
  file(APPEND "${log}" "COMMAND: ${ARGV}\n${stdout}\n${stderr}\nRESULT: ${result}\n")
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "SDK verification failed: ${ARGV}\n${stdout}\n${stderr}\nLog: ${log}")
  endif()
endfunction()
checked("${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config "${CONFIG}" --prefix "${root}/staging")
# Exercise relocation: no build or execution uses the original install prefix.
file(RENAME "${root}/staging" "${root}/relocated SDK ä")
set(sdk "${root}/relocated SDK ä")
set(work "${root}/Consumer ä")
file(MAKE_DIRECTORY "${work}")
file(COPY "${sdk}/examples/pendulum/main.c" "${sdk}/examples/pendulum/analysis.c"
  "${CMAKE_CURRENT_LIST_DIR}/sdk_probe.c" DESTINATION "${work}")
file(WRITE "${work}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.24)
project(InstalledPhysimConsumer LANGUAGES C)
include("${PHYSIM_SDK}/cmake/PhysimExperiment.cmake")
add_executable(sdk_probe sdk_probe.c)
target_link_libraries(sdk_probe PRIVATE physim_sdk)
add_subdirectory("${PHYSIM_SDK}/examples/language" language)
foreach(name energy motion flight_phases sampling phase_space rotation_path particles rigid_body contacts distance_joints constraint_graph sweeps coordinate_frames optional_values optional_bindings language_body language_contact language_joint language_graph language_sweep language_pendulum language_projectile
             language_spring language_sensors language_analysis language_integral language_sensor_analysis)
  file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${name}-$<CONFIG>.cmake" CONTENT
    "set(${name} [==[$<TARGET_FILE:${name}>]==])\n")
endforeach()
foreach(name projectile collision box_floor spring uncertain_projectile box_collision buoyancy)
  add_library(${name} MODULE "${PHYSIM_SDK}/examples/${name}/main.c")
  target_link_libraries(${name} PRIVATE physim_sdk)
  set_target_properties(${name} PROPERTIES PREFIX "")
endforeach()
file(GLOB headers "${PHYSIM_SDK}/include/physim/*.h")
set(sources)
foreach(header IN LISTS headers)
  get_filename_component(name "${header}" NAME)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${name}.c" "#include <physim/${name}>\n")
  list(APPEND sources "${CMAKE_CURRENT_BINARY_DIR}/${name}.c")
endforeach()
add_library(header_probe OBJECT ${sources})
target_include_directories(header_probe PRIVATE "${PHYSIM_SDK}/include")
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/paths-$<CONFIG>.cmake" CONTENT
"set(probe [==[$<TARGET_FILE:sdk_probe>]==])\nset(analysis [==[$<TARGET_FILE:analysis>]==])\nset(pendulum [==[$<TARGET_FILE:experiment>]==])\n")
foreach(name projectile collision box_floor spring uncertain_projectile box_collision buoyancy)
  file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${name}-$<CONFIG>.cmake" CONTENT
    "set(${name} [==[$<TARGET_FILE:${name}>]==])\n")
endforeach()
]=])
load_cache("${BUILD_DIR}" READ_WITH_PREFIX original_ CMAKE_GENERATOR CMAKE_GENERATOR_PLATFORM
  CMAKE_GENERATOR_TOOLSET CMAKE_C_COMPILER CMAKE_MAKE_PROGRAM)
set(generator -G "${original_CMAKE_GENERATOR}")
if(original_CMAKE_GENERATOR_PLATFORM)
  list(APPEND generator -A "${original_CMAKE_GENERATOR_PLATFORM}")
endif()
if(original_CMAKE_GENERATOR_TOOLSET)
  list(APPEND generator -T "${original_CMAKE_GENERATOR_TOOLSET}")
endif()
checked("${CMAKE_COMMAND}" -S "${work}" -B "${work}/build" ${generator}
  "-DPHYSIM_SDK=${sdk}" "-DCMAKE_C_COMPILER=${original_CMAKE_C_COMPILER}"
  "-DCMAKE_MAKE_PROGRAM=${original_CMAKE_MAKE_PROGRAM}" "-DCMAKE_BUILD_TYPE=${CONFIG}")
checked("${CMAKE_COMMAND}" --build "${work}/build" --config "${CONFIG}" --parallel 4)
include("${work}/build/paths-${CONFIG}.cmake")
set(exe "")
if(CMAKE_HOST_WIN32)
  set(exe .exe)
endif()
foreach(name pendulum projectile collision box_floor spring uncertain_projectile box_collision buoyancy)
  if(NOT name STREQUAL "pendulum")
    include("${work}/build/${name}-${CONFIG}.cmake")
  endif()
  set(run "${root}/${name}.psrun")
  set(report "${root}/${name}-report")
  checked("${sdk}/bin/physim-runner${exe}" "${${name}}" "${run}" --steps 200 --dt .005 --seed 42)
  checked("${sdk}/bin/physim-analysis-runner${exe}" "${analysis}" "${run}" "${report}")
  checked("${probe}" "${run}" "${report}.psreport")
  message(STATUS "Installed SDK: ${name} passed")
endforeach()
foreach(name energy motion flight_phases sampling phase_space rotation_path particles rigid_body contacts distance_joints constraint_graph sweeps coordinate_frames optional_values optional_bindings language_body language_contact language_joint language_graph language_sweep language_pendulum language_projectile
             language_spring language_sensors language_analysis language_integral language_sensor_analysis)
  include("${work}/build/${name}-${CONFIG}.cmake")
endforeach()
foreach(name energy motion flight_phases sampling phase_space rotation_path particles rigid_body contacts distance_joints constraint_graph sweeps coordinate_frames optional_values optional_bindings)
  checked("${${name}}")
  message(STATUS "Installed SDK language program: ${name} passed")
endforeach()
foreach(name language_pendulum language_projectile language_spring language_sensors language_body language_contact language_joint language_graph language_sweep)
  set(run "${root}/${name}.psrun")
  checked("${sdk}/bin/physim-runner${exe}" "${${name}}" "${run}" --steps 200 --dt .005 --seed 42)
  foreach(analyzer language_analysis language_integral)
    set(report "${root}/${name}-${analyzer}")
    checked("${sdk}/bin/physim-analysis-runner${exe}" "${${analyzer}}" "${run}" "${report}")
    checked("${probe}" "${run}" "${report}.psreport" language)
  endforeach()
  if(name STREQUAL "language_sensors")
    set(report "${root}/${name}-sensor-analysis")
    checked("${sdk}/bin/physim-analysis-runner${exe}" "${language_sensor_analysis}" "${run}" "${report}")
    checked("${probe}" "${run}" "${report}.psreport" sensor-language)
  endif()
  if(name STREQUAL "language_sensors" OR name STREQUAL "language_body" OR name STREQUAL "language_contact" OR name STREQUAL "language_joint" OR name STREQUAL "language_graph" OR name STREQUAL "language_sweep")
    set(report "${root}/${name}-c-analysis")
    checked("${sdk}/bin/physim-analysis-runner${exe}" "${analysis}" "${run}" "${report}")
    checked("${probe}" "${run}" "${report}.psreport")
  endif()
  message(STATUS "Installed SDK language experiment and analyses: ${name} passed")
endforeach()
file(WRITE "${root}/PASSED.txt" "Eight C templates, all language examples rebuilt, fifteen language programs executed, nine language experiments with both general language analyses, specialized sensor analysis with scatter and tables, standalone headers, installed runners, validated runs and reports passed.\n")
message(STATUS "SDK verification passed. Evidence: ${root}")
