cmake_minimum_required(VERSION 3.24)
if(NOT PHYSIM_SDK)
  message(FATAL_ERROR "Set PHYSIM_SDK to the Physim SDK directory")
endif()
set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
foreach(config Debug Release)
  string(TOUPPER ${config} CONFIG)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG} "${CMAKE_BINARY_DIR}/bin")
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG} "${CMAKE_BINARY_DIR}/bin")
endforeach()
add_library(physim_sdk STATIC "${PHYSIM_SDK}/src/core.c" "${PHYSIM_SDK}/src/memory.c" "${PHYSIM_SDK}/src/array.c" "${PHYSIM_SDK}/src/string_view.c" "${PHYSIM_SDK}/src/hashmap.c" "${PHYSIM_SDK}/src/math.c" "${PHYSIM_SDK}/src/data.c" "${PHYSIM_SDK}/src/analysis.c" "${PHYSIM_SDK}/src/scene.c" "${PHYSIM_SDK}/src/numerics.c" "${PHYSIM_SDK}/src/units.c" "${PHYSIM_SDK}/src/series.c" "${PHYSIM_SDK}/src/report.c" "${PHYSIM_SDK}/src/report_export.c" "${PHYSIM_SDK}/src/mechanics.c" "${PHYSIM_SDK}/src/box_contacts.c" "${PHYSIM_SDK}/src/collision.c" "${PHYSIM_SDK}/src/measurement.c")
set_target_properties(physim_sdk PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(physim_sdk PUBLIC "${PHYSIM_SDK}/include")
if(MSVC)
  add_compile_options(/W4 /utf-8)
  add_compile_definitions(_CRT_SECURE_NO_WARNINGS)
else()
  add_compile_options(-Wall -Wextra -Wpedantic)
  target_compile_definitions(physim_sdk PRIVATE _POSIX_C_SOURCE=200809L)
  target_link_libraries(physim_sdk PUBLIC m)
endif()
set(experiment_source main.c)
set(analysis_source analysis.c)
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/physim.project")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/physim.project")
  file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/physim.project" experiment_entry REGEX "^experiment=")
  list(LENGTH experiment_entry experiment_count)
  if(experiment_count GREATER 1)
    message(FATAL_ERROR "Duplicate experiment entry in physim.project")
  endif()
  if(experiment_count EQUAL 1)
    string(REGEX REPLACE "^experiment=" "" experiment_source "${experiment_entry}")
  endif()
  file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/physim.project" analysis_entry REGEX "^analysis=")
  list(LENGTH analysis_entry analysis_count)
  if(analysis_count GREATER 1)
    message(FATAL_ERROR "Duplicate analysis entry in physim.project")
  endif()
  if(analysis_count EQUAL 1)
    string(REGEX REPLACE "^analysis=" "" analysis_source "${analysis_entry}")
  endif()
endif()
if(experiment_source STREQUAL "main.phys")
  include("${PHYSIM_SDK}/cmake/PhysimLanguage.cmake")
  physim_add_experiment(experiment main.phys)
elseif(experiment_source STREQUAL "main.c")
  add_library(experiment MODULE main.c)
else()
  message(FATAL_ERROR "Unsupported experiment source; use main.c or main.phys")
endif()
if(analysis_source STREQUAL "analysis.phys")
  include("${PHYSIM_SDK}/cmake/PhysimLanguage.cmake")
  physim_add_analysis(analysis analysis.phys)
elseif(analysis_source STREQUAL "analysis.c")
  add_library(analysis MODULE analysis.c)
else()
  message(FATAL_ERROR "Unsupported analysis source; use analysis.c or analysis.phys")
endif()
foreach(target experiment analysis)
  target_link_libraries(${target} PRIVATE physim_sdk)
  set_target_properties(${target} PROPERTIES PREFIX "")
endforeach()
