foreach(required COMPILER SOURCE OUTPUT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
if(NOT MODE)
  set(MODE --emit-c)
endif()
set(module_arguments)
foreach(path IN LISTS MODULE_PATHS)
  list(APPEND module_arguments --module-path "${path}")
endforeach()
execute_process(COMMAND "${COMPILER}" "${MODE}" ${module_arguments} "${SOURCE}"
  OUTPUT_FILE "${OUTPUT}.tmp" RESULT_VARIABLE result TIMEOUT 30)
if(NOT result EQUAL 0)
  file(REMOVE "${OUTPUT}.tmp")
  message(FATAL_ERROR "physimc failed (${result}); see source diagnostic above")
endif()
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
