include_guard(GLOBAL)
cmake_minimum_required(VERSION 3.24)

function(physim_language_target kind target source)
  cmake_parse_arguments(PHYSIM "" "" "MODULE_PATHS" ${ARGN})
  if(PHYSIM_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unknown Physim language target arguments: ${PHYSIM_UNPARSED_ARGUMENTS}")
  endif()
  get_filename_component(sdk "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  if(PHYSIM_SDK)
    set(sdk "${PHYSIM_SDK}")
  endif()
  if(TARGET physimc)
    set(compiler "$<TARGET_FILE:physimc>")
    set(compiler_dependency physimc)
  elseif(PHYSIM_COMPILER)
    set(compiler "${PHYSIM_COMPILER}")
    set(compiler_dependency "${PHYSIM_COMPILER}")
  else()
    find_program(compiler NAMES physimc HINTS "${sdk}/bin" REQUIRED)
    set(compiler_dependency "${compiler}")
  endif()
  get_filename_component(input "${source}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  get_filename_component(module_dir "${input}" DIRECTORY)
  file(GLOB_RECURSE module_sources CONFIGURE_DEPENDS "${module_dir}/*.phys")
  set(module_paths)
  foreach(path IN LISTS PHYSIM_MODULE_PATHS)
    get_filename_component(absolute_path "${path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    list(APPEND module_paths "${absolute_path}")
    file(GLOB_RECURSE additional_sources CONFIGURE_DEPENDS "${absolute_path}/*.phys")
    list(APPEND module_sources ${additional_sources})
  endforeach()
  set(output "${CMAKE_CURRENT_BINARY_DIR}/${target}.physim.c")
  set(driver "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/PhysimEmitC.cmake")
  set(mode --emit-c)
  if(kind STREQUAL "MODULE")
    set(mode --emit-experiment)
  elseif(kind STREQUAL "ANALYSIS")
    set(mode --emit-analysis)
  endif()
  add_custom_command(OUTPUT "${output}"
    COMMAND "${CMAKE_COMMAND}" "-DCOMPILER=${compiler}" "-DSOURCE=${input}" "-DOUTPUT=${output}" "-DMODE=${mode}" "-DMODULE_PATHS=${module_paths}" -P "${driver}"
    DEPENDS "${input}" ${module_sources} ${compiler_dependency} "${driver}"
    COMMENT "Compiling ${source} with physimc" VERBATIM)
  if(kind STREQUAL "MODULE" OR kind STREQUAL "ANALYSIS")
    add_library(${target} MODULE "${output}")
    set_target_properties(${target} PROPERTIES PREFIX "")
  else()
    add_executable(${target} "${output}")
  endif()
  if(TARGET physim_core)
    target_link_libraries(${target} PRIVATE physim_core)
  elseif(TARGET physim_sdk)
    target_link_libraries(${target} PRIVATE physim_sdk)
  else()
    if(NOT TARGET physim_language_sdk)
      set(core_sources)
      foreach(name core memory array string_view hashmap math data analysis scene numerics units
                   series report report_export mechanics box_contacts collision measurement)
        list(APPEND core_sources "${sdk}/src/${name}.c")
      endforeach()
      add_library(physim_language_sdk STATIC ${core_sources})
      set_target_properties(physim_language_sdk PROPERTIES POSITION_INDEPENDENT_CODE ON)
      target_include_directories(physim_language_sdk PUBLIC "${sdk}/include")
      target_compile_features(physim_language_sdk PRIVATE c_std_17)
      if(MSVC)
        target_compile_options(physim_language_sdk PRIVATE /utf-8)
        target_compile_definitions(physim_language_sdk PRIVATE _CRT_SECURE_NO_WARNINGS)
      else()
        target_compile_definitions(physim_language_sdk PRIVATE _POSIX_C_SOURCE=200809L)
        target_link_libraries(physim_language_sdk PUBLIC m)
      endif()
    endif()
    target_link_libraries(${target} PRIVATE physim_language_sdk)
  endif()
  target_compile_features(${target} PRIVATE c_std_17)
  set_target_properties(${target} PROPERTIES C_EXTENSIONS OFF)
  target_include_directories(${target} PRIVATE "${sdk}/include")
  if(MSVC)
    target_compile_options(${target} PRIVATE /utf-8 /fp:strict)
  else()
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(${target} PRIVATE -fno-fast-math -ffp-contract=off)
    endif()
    if(NOT WIN32)
      target_link_libraries(${target} PRIVATE m)
    endif()
  endif()
endfunction()
function(physim_add_program target source)
  physim_language_target(EXECUTABLE "${target}" "${source}" ${ARGN})
endfunction()
function(physim_add_experiment target source)
  physim_language_target(MODULE "${target}" "${source}" ${ARGN})
endfunction()
function(physim_add_analysis target source)
  physim_language_target(ANALYSIS "${target}" "${source}" ${ARGN})
endfunction()
